### ISSUE TITLE
Beautiful app

### ISSUE THREAD

**Issue by Baker0o7** [Bnyro/TranslateYou#1]
Thank you for the app please add floating button👍

**Comment by Bnyro** [comment]
Thanks for your feedback <3
Adding a floating button is not an issue, I just need to know what it should be used for ;)

**Comment by Bnyro** [comment]
It could be used for either pasting text or copying, clearing, or sharing the translated text :)

**Comment by Baker0o7** [comment]
Yes similar to google translater floating button

**Comment by Bnyro** [comment]
https://github.com/Bnyro/TranslateYou/commit/5bea6842f4317e32ea29490247ef014b0e89b7e5
