### ISSUE TITLE
Lingva Translate

### ISSUE THREAD

**Issue by Bnyro** [Bnyro/TranslateYou#10]
### Describe your suggested feature

I'm thinking about adding support for [LingvaTranslate](https://github.com/thedaviddelta/lingva-translate).
Just curious whether anyone would like to have the option to use that instead of LibreTranslate since Lingva uses the Goggle Translator and therefore provides much better results than LibreTranslate does.
Any opinions on that are welcome!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
I think this'll be good than LibreTranslate. I mean... It can't even translate basic words

**Comment by cypherpunk1984** [comment]
Whenever I had tried LibreTranslate website, it almost never gave me good results.
Simple Translate and Lingva Translate are the ones that work great.
They are both FOSS frontends for Google Translate.
Simple Translate offers 3 other translation engines to select), and has tons of instances on clearnet, tor network, l2p and even on LOKI network.

Simple Translate android app offers some cool features, but sadly is kind of abandoned:
https://manerakai.github.io/simplytranslate_mobile/

There are 2 android apps for Lingva Translate that I know of:
https://github.com/yaxarat/lingvaandroid
https://github.com/MahanRahmati/translate

**Comment by Bnyro** [comment]
I just have been checking the other 2 engines SimplyTranslate supports and I don't think it's worth using SimplyTranslate for them. Since LibreTranslate is already supported directly without ST in between, I think it would more sense to support Lingva rather than SimplyTranslate. Or maybe I'll just add support for all of them if I find the time for it :)

**Comment by Bnyro** [comment]
Hey @IzzySoft,

I created two flavors now:
1. `libre`, Package name: `com.bnyro.translate.libre`, App label: `Translate You Libre` (only supports LibreTranslate)
2. `normal`, Package name: `com.bnyro.translate`, App label: `Translate You` (included support for Lingva and LibreTranslate)

Should I just upload both apks somehow at the next release, or what we would be the best way for you? :)

**Comment by IzzySoft** [comment]
You can upload both. Just let me know in advance

* if both use the same applicationId
* if not, whether I shall pull both
* if the "libre" one kept the original ApplicationId
* which file names you plan to use (so I can adjust my config accordingly should you attach both)

Note I won't be available for the next ~36h, so if I need to adjust something we better have the release a day later :wink:

**Comment by Bnyro** [comment]
>     * if the "libre" one kept the original ApplicationId
> 
The version with support for Lingva keeps the old applicationId, the one with LibreTranslate will use `.libre` as suffix (`com.bnyro.translate.libre`)
>     * which file names you plan to use (so I can adjust my config accordingly should you attach both)
> 
I would use `app-release.apk` as file name for the non-free version and `app-release-libre.apk` as file name for the libre version if that's okay.

> Note I won't be available for the next ~36h, so if I need to adjust something we better have the release a day later wink
>
Alright, I was planning to do it either Thursday or the weekend, I won't risk doing it without you ;)

**Comment by IzzySoft** [comment]
Sounds good. Just that the current users (`com.bnyro.translate`) will be "updated" to the non-libre version this way. Your choice of course. You want me to host both variants then? Or should I skip the non-libre (disabling updates and instead placing a note to switch to the libre one) first to avoid the mentioned problem? Then there won't be an automated update to them but they have to choose for themselves.

For the transition, it would also be possible to build the libre flavor with the non-libre ApplicationId and add a flash screen for the next start informing about the change, then wait a few days/weeks before performing it. This would allow us to serve both variants via my repo hopefully without anyone having anything to complain.

**Comment by Bnyro** [comment]
> Sounds good. Just that the current users (`com.bnyro.translate`) will be "updated" to the non-libre version this way. Your choice of course. You want me to host both variants then? Or should I skip the non-libre (disabling updates and instead placing a note to switch to the libre one) first to avoid the mentioned problem? Then there won't be an automated update to them but they have to choose for themselves.
> 
Oh, right, that makes sense. I should probably change it so that the libre version is the default to not let users automatically update the app to the non-free version without realizing it, I will change that before the update and inform you then once again :)
> For the transition, it would also be possible to build the libre flavor with the non-libre ApplicationId and add a flash screen for the next start informing about the change, then wait a few days/weeks before performing it. This would allow us to serve both variants via my repo hopefully without anyone having anything to complain.
>
Yeah, that's a good idea too, but I think it's better to just keep the current version libre as you suggested previously, anything else would be a weird move :wink:

**Comment by IzzySoft** [comment]
Yes, that will be best! As the file names in the attachments are independent from whatever naming you decide for ApplicationId: Shall I already update my config to only pick APKs with the term `libre` in their name? Then you'd be free to create the new release anytime, and we'd just add the second app afterwards.

**Comment by Bnyro** [comment]
> Yes, that will be best! As the file names in the attachments are independent from whatever naming you decide for ApplicationId: Shall I already update my config to only pick APKs with the term `libre` in their name?
>
Yes, that would be perfect, thank you!

**Comment by Bnyro** [comment]
The app even needs more storage space than LibreTube now, that's definitely not normal :/
Do you have an idea whether it could be related to the different available build flavors?

**Comment by IzzySoft** [comment]
30 M is correct – per app. These are two apps now, so each has its own limit.

The storage thingy sounds weird. Applies to both, or just the NF? My first look would be what the cat dragged in: running

    gradle :app:dependencies

might give you a surprise. And maybe we postpone adding the nf until we figured what's going on?

**Comment by Bnyro** [comment]
Oh, found the issue, I've messed up with the proguard rules ;)

**Comment by Bnyro** [comment]
I typed `,` instead of `.`, took me one hour to find that ...

**Comment by IzzySoft** [comment]
Oh my, those are hard to spot. I remember something similar with some regexp logic in fdroidclient: one opening parenthesis at the wrong point spoiled the whole thing: instead of "if WiFi OR mobile data are active" it demanded both to be active to perform update checks automatically :scream: Took us half a year to figure :see_no_evil: (actually, at that point someone started looking at the expression as a possible culprit)

**Comment by Bnyro** [comment]
Hey @IzzySoft,
Sorry to ping you again -_-
I would appreciate if you could add the non-free version to your repo too now, future releases will follow the same format (`app-release.apk` for the non-free version, `app-release-libre.apk` for the libre version.
Cheers and thanks in advance

**Comment by IzzySoft** [comment]
OK, cloned the metadata and adjusted the `full_description.txt` of the new app to point out the differences. Can we have a separate fastlane tree for that, so future updates to the description would be reflected automatically? My updater supports any "starting point" for that, so you could e.g. place it in `app/standard/fastlane`. If you don't plan for different screenshots and icon, just the descriptions suffice (I'd then symlink the images folder on my end), otherwise set it up complete.

Oh, and it might be a good idea to give the non-free APK a more dedicated name. `app-release.apk` is the generic name for an APK by a release build. No prob for my updater (I simply put the cart in front of the horse and told it which name to *ignore* instead of which to pick), but it would be more clear then. Plus who knows what 3rd APK you might plan one day :wink:

**Comment by Bnyro** [comment]
> OK, cloned the metadata and adjusted the `full_description.txt` of the new app to point out the differences. Can we have a separate fastlane tree for that, so future updates to the description would be reflected automatically? My updater supports any "starting point" for that, so you could e.g. place it in `app/standard/fastlane`. If you don't plan for different screenshots and icon, just the descriptions suffice (I'd then symlink the images folder on my end), otherwise set it up complete.
>
Perfect, I'll set up a different directory containing a different description tomorrow and inform you then, thanks!
> Oh, and it might be a good idea to give the non-free APK a more dedicated name. `app-release.apk` is the generic name for an APK by a release build. No prob for my updater (I simply put the cart in front of the horse and told it which name to *ignore* instead of which to pick), but it would be more clear then. Plus who knows what 3rd APK you might plan one day :wink:
>
Yeah, that's true. I just don't want to call it `non-free` because the app version itself is free in fact, it only calls Foss APIs that fetch unfree APIs :joy:
But you're right, a different name for the release would probably be more convenient for users, I should probably also add a section about it to the README to avoid confusion about it :wink:

**Comment by IzzySoft** [comment]
Neutral suggestion: `app-release-plus.apk` (as it adds "something" :wink:) And thanks, looking forward to your next ping then!

**Comment by Bnyro** [comment]
> Neutral suggestion: `app-release-plus.apk` (as it adds "something" 😉)
>
Sounds good, unfortunately I can't name the build version like that because `plus` is a recognized function in Groovy and will be handled as such instead of just being treated as a string, at least I can't get it working :joy:
I'll just keep it standard for now until I figure out how to name it like that :wink:

I created a folder called `standard` now that contains the default fastlane tree for the non-free version, currently only the `full_decription.txt` and the `short_description.txt`. I don't think adding different screenshots, etc. is needed at the moment :)

**Comment by IzzySoft** [comment]
> Sounds good, unfortunately I can't name the build version like that because `plus` is a recognized function in Groovy and will be handled as such

How about `multi` then? Or `lingva` (though that might imply no other engines will ship)… But `standard` is fine, too. I chose that because it already existed – so I wonder which folder you've added now. Will look and see … ah, in the root. I meant just placing it inside the existing [`standard` directory](https://github.com/Bnyro/TranslateYou/tree/master/app/standard), next to its `release` one. Keeps the root clean. But the other is fine with me if you prefer. Just decide which it should be (move if needed) and let me know. And yes, agreed: currently, the main purpose is to have the description clear.

**Comment by Bnyro** [comment]
> How about `multi` then? Or `lingva` (though that might imply no other engines will ship)… But `standard` is fine, too. I chose that because it already existed
>
True, that would be an idea too, but the libre version might get a second engine too in the future, who knows whether there will be some new open source ones in the future ;)
> – so I wonder which folder you've added now. Will look and see … ah, in the root. I meant just placing it inside the existing [`standard` directory](https://github.com/Bnyro/TranslateYou/tree/master/app/standard), next to its `release` one. Keeps the root clean. But the other is fine with me if you prefer. Just decide which it should be (move if needed) and let me know.
>
Alright, changed it now, I just didn't want to do that before because I blocked these directories with the `.gitignore`, the affected lines got removed now :)
So it should now be as you suggested to :wink:

**Comment by IzzySoft** [comment]
OK, fine – then let's leave it at "standard" (other project often use "foss" and "play", but :man_shrugging:). Now you've just to fix the files:

* `short_description` is limited to 80 chars, everything after that will be truncated. I'd suggest to remove the word "built".
* `full_description` lacks some line breaks to keep the paragraphs separated (so my engine can correctly process it as Markdown – looks much better as using `nl2br` on the plain text, believe me).

I've already updated the YAML accordingly, so please make sure to have it fixed before you tag the next release  :wink:

Should you one day want to bring both apps to F-Droid.org I can check again how we get Fastlane working there. F-Droid supports flavors with Fastlane, too – I'd just need to check again where you'd need to place the structure then. Ah, stupid me, it's all in [my snippet](https://gitlab.com/-/snippets/1895688#locations) :see_no_evil:

**Comment by Ilithy** [comment]
> short_description is limited to 80 chars, everything after that will be truncated. I'd suggest to remove the word "built".
> full_description lacks some line breaks to keep the paragraphs separated (so my engine can correctly process it as Markdown – looks much better as using nl2br on the plain text, believe me).

Hi;
I had added a [validator](https://github.com/Bnyro/TranslateYou/blob/master/.github/workflows/validate-store-files.yml) for presentation files (created by @TrianguloY) to automatically check the number of characters present, but I don't know how to make it check both versions of the presentations of the app...(currently it only checks in the ./fastlane/metadata/android folder)...

**Comment by IzzySoft** [comment]
Ugh, now "standard" fastlane is in `app/standard/standard/fastlane` (double-standard) and its `full_description.txt` has just a single line? What I had in mind was rather something like this:

```markdown
<i>Translate You</i> is a Translator App built with <a href="https://m3.material.io/">Material Design 3 (You)</a> supporting different translation engines. Supported engines are <a href="https://github.com/LibreTranslate/LibreTranslate">LibreTranslate</a>, which supports more than 30 languages and <a href="https://github.com/thedaviddelta/lingva-translate">LingvaTranslate</a> which uses Google Translate as a backend, thus causing the NonFreeNet anti-feature.

There's also a <a href="https://apt.izzysoft.de/packages/com.bnyro.translate/">libre version</a> of the app which refrains from using Lingva and therefore doesn't have the anti-feature.
```

(see [here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for formatting hints). If it should be a single paragraph by choice, that's of course fine as-is now. Apart from the double-standard maybe – which either you need to revert, or I need to update in the YAML here :wink: 

> Currently the app benefits from your repo's blazingly fast updates as well as your technical support, so currently I'm really happy with the situation, but I'll keep it in mind :)

Thanks for the kind words – and fine with me :smiley:

**Comment by Bnyro** [comment]
> Ugh, now "standard" fastlane is in `app/standard/standard/fastlane` (double-standard)
>
Damn, I forgot that the directory already exists when doing `mv standard app/standard` :joy:
>and its `full_description.txt` has just a single line? What I had in mind was rather something like this:
> 
> ```gfm
> <i>Translate You</i> is a Translator App built with <a href="https://m3.material.io/">Material Design 3 (You)</a> supporting different translation engines. Supported engines are <a href="https://github.com/LibreTranslate/LibreTranslate">LibreTranslate</a>, which supports more than 30 languages and <a href="https://github.com/thedaviddelta/lingva-translate">LingvaTranslate</a> which uses Google Translate as a backend, thus causing the NonFreeNet anti-feature.
> 
> There's also a <a href="https://apt.izzysoft.de/packages/com.bnyro.translate/">libre version</a> of the app which refrains from using Lingva and therefore doesn't have the anti-feature.
> ```
> 
Whoops, I just copied your suggestion now to be sure, thanks :)
> Thanks for the kind words – and fine with me 😃
>
Thanks for still being here and helping me and other devs of small Foss apps :wink:

**Comment by IzzySoft** [comment]
Cool – then everything should be in place now. Please keep watch once you've made the next release to see that everything was updated as it should. If something looks weird, yell and I'll take another look (ICE I can trigger a pure Fastlane-update manually, too).

**Comment by shuvashish76** [comment]
@Bnyro Request to add info in fastlane about Lingva for F-Droid users for transparency, though it's clearly mentioned on GitHub.
Something like :
> NOTE: Lingva uses Google Translate® to fetch translations, which is disabled by default.
