### ISSUE TITLE
Simply Translate not working

### ISSUE THREAD

**Issue by GET100PERCENT** [Bnyro/TranslateYou#106]
### Steps to reproduce

1. Choose the simplytranslate engine in the settings.
2. Then try to translate some text.

### Expected behavior

It should translate as usual.

### Actual behavior

It shows "Error in communicating with the server."

### Translate You version

2.7

### Android version

7.1

### Other details

Other engines works well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Works fine for me, I either assume the official instance is geo-blocked for you or had an outage.

**Comment by GET100PERCENT** [comment]
Okay 👍

**Comment by GET100PERCENT** [comment]
Now it also worked for me
