### ISSUE TITLE
Monochromatic icon issue in Android 13

### ISSUE THREAD

**Issue by reinhart1010** [Bnyro/TranslateYou#112]
### Steps to reproduce

1. Install app on Android 13 device
2. Enable monochromatic icons on the system-wide theme settings

### Expected behavior

The icon should be visible on the home screen

### Actual behavior

Blank filled icon. 
![Screenshot_20221220_191252_One UI Home](https://user-images.githubusercontent.com/17312341/208665115-c80598ce-0e87-4639-b262-4fc059a2fa64.jpg)
![Screenshot_20221220_191552_One UI Home](https://user-images.githubusercontent.com/17312341/208665467-3a478f4d-b7d0-47d1-9a8a-f60532e7e126.jpg)

### Translate You version

1.3

### Android version

Android 13

### Other details

Looks like the `ic_launcher_foreground.xml` contains a solid background behind the app icon's logomark. This should be removed according to Android's adaptive icon standards.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by reinhart1010** [comment]
The screenshots are captured from a Samsung device running Android 13. If you would like to test/reproduce using Android Studio's official emulators, the app icon must be pinned into the home screen (instead of the app drawer).

**Comment by Bnyro** [comment]
I can't seem to reproduce it, neither via my personal device nor with the emulator (both Android 13). The `ic_launcher_foreground.xml` doesn't contain a solid background, so I doubt that's the issue.
If you have an idea, feel free to create a PR, otherwise I don't see anything I could do about it.

**Comment by Ilithy** [comment]
@Bnyro Same things on my device (Pixel 6 pro - GrapheneOS under Android 13)

![Screenshot_20221227-170010](https://user-images.githubusercontent.com/36798218/209691181-72d3b61d-a1e7-4229-822f-137102180876.png)
