### ISSUE TITLE
Characters counter

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#113]
### Describe your suggested feature

In order to fit many social apps characters restrictions I would like to have a characters counter in top of the bar that decrease as words one write.

Somewhere in the app I’ll set the limit I need (it can vary from social to social)

**Comment by Bnyro** [comment]
So you want to see the characters count of translated text as well as an option to limit the size of the text that is actually being shared when using the share button in the top app bar?

**Comment by Bnyro** [comment]
There's an option for a warning now with https://github.com/Bnyro/TranslateYou/commit/b4841bb79b10bbc6741258a6bedd751125b35f63, not sure where to place a character counter.

**Comment by Bnyro** [comment]
Sure, I can add a check mark and the other limits as well. Though my question is whether you still "need" a real-time character counter or whether we can complete the issue with the warning when the limit is reached?

**Comment by Bnyro** [comment]
Added your suggestions (checkmark and more character limits), going to leave it without a character counter for now as I don't know where to place it.
