### ISSUE TITLE
Multiple sessions at once

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#114]
Sometimes It happens that one need to translate a website content while chat with a foreign friend in WhatsApp, simultaneously.

So with (up to 3) tabs one can easily switch between translations without lost anything.

**Comment by Bnyro** [comment]
Any suggestions/ideas design-wise?

**Comment by Bnyro** [comment]
I neither want to remove the app title from the top nor add an app drawer (=sidebar) to the app only for that purpose.

I would have thought of a similar design as the `Simultaneous translation` features instead, but I don't know where to place it honestly.

**Comment by Bnyro** [comment]
I might give it a try in the next days, although I'm not sure whether sliding will be possible in the end.

**Comment by Bnyro** [comment]
Not planned for now, sorry.
