### ISSUE TITLE
SimplyTranslate doesn't work

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#115]
### Steps to reproduce

1. Choose SimplyTranslate as a translate engine
2. Translate from any language to any language any word/phrase/etc

### Expected behavior

Should appear translation

### Actual behavior

Nothing appears below

### Translate You version

2.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Works fine for me, please make sure https://simplytranslate.org/ loads for you and try an instance from https://simple-web.org/projects/simplytranslate.html if it doesn't load.

**Comment by HotarunIchijou** [comment]
So, app's reinstalling has fixed this issue
