### ISSUE TITLE
Translation covered by description if keyboard is open

### ISSUE THREAD

**Issue by glemco** [Bnyro/TranslateYou#117]
### Steps to reproduce

Type something on some engine with a description (e.g. lingva) or with detected language and keep the keyboard open.

### Expected behavior

The box containing the translation should stay on top, so that I'm able to see that first (as that's the actual content a user is interested in), any other info can be accessible with scroll or closing the keyboard.
In the screenshots you can see that the translation is visible only without keyboard.
<img src="https://user-images.githubusercontent.com/32201227/209448491-633d4158-e96f-4252-8e57-2ba5892b2f20.png" width="45%"/> <img src="https://user-images.githubusercontent.com/32201227/209448517-c0bafe74-7265-451a-a6fa-a7ea5d058df8.png" width="45%"/>

### Actual behavior

The text boxes with the description and/or detected language cover the actual translation if there isn't enough space (keyboard is open, at least on my setup).

### Translate You version

2.7

### Android version

Android 12.1

### Other details

The keyboard I'm using is AnySoftKeyboard (maybe a little bigger than the default) but I assume this layout can be problematic also on phones with low resolution.

Thanks in advance, very nice app anyway, great to have a good and open source translator. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thank you for using the app and your positive feedback!
I've noticed the issue as well, we're now only showing the additional information (e.g. definitions) when the keyboard is not visible. It works fine for the default Android keyboard now at least, I hope it does so as well with the AnySoft Keyboard!

**Comment by glemco** [comment]
Great, thanks for the quick fix!
