### ISSUE TITLE
Transliteration below the translate

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#118]
### Describe your suggested feature

Like in google translate, for example, english transliteration should appear below the translated word/phrase/text/etc
![reverso_example](https://user-images.githubusercontent.com/113282550/209476078-050bfc69-d99d-45dc-8548-fe2dbdf40dea.png)
![gtranslate_example](https://user-images.githubusercontent.com/113282550/209476079-9d3216b7-6efb-42ec-b080-a91f88852e92.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I had a quick look and it seems like only Lingva Translate and the Reverso Context Engine support transliterations so it will only be visible for those. Apart from that I'm thinking of showing it at the bottom on top of the other additional information results to make it integrate better with the current UI.

**Comment by HotarunIchijou** [comment]
> I'm thinking of showing it at the bottom on top of the other additional information
But then the distance between translate and transliteration will be too large, isn't it?

**Comment by Bnyro** [comment]
Yes, but when doing differently there would be issues with the size of both the text view, the one for inserting text as well as the one showing the translation. Apart from that it would probably make #79 even worse.

**Comment by Bnyro** [comment]
It doesn't seem to be available often though so it will appear very rarely anyways.

**Comment by HotarunIchijou** [comment]
Sadly. But maybe additional information should be shown out of the text box, below this? Then it may fix [https://github.com/Bnyro/TranslateYou/issues/79](#79) issue, I think
