### ISSUE TITLE
For what this button is?

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#119]
### Describe your suggested feature

![button](https://user-images.githubusercontent.com/113282550/209570697-2752269c-2316-4da6-99f2-18d51e6f7279.png)
I really can't understand, for what this button.

![button2](https://user-images.githubusercontent.com/113282550/209571001-4110bf95-e873-480a-a607-0c3d16004207.png)
Sometimes this button overlaps suggestions and after all it attracts too much attention to itself

![yetanotherbutton](https://user-images.githubusercontent.com/113282550/209570960-803e8fee-3b69-40d5-a2d3-89e86efeb35e.png)
For text clearing we have this button

### Other details

So, in my opinion, this button should be removed, because it's really unneeded

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Indeed, both buttons serve the same functionality currently, I agree that the button could be removed in order to save that space.
