### ISSUE TITLE
Drag the entire body of text (without spliting in two directions)

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#12]
### Describe your suggested feature

When I scroll the text body only lower side of the screen follow the desired direction.
This takes advantage of only half of the screen while I would like to take advantage of the full length available.
To improve readability I wish a single body that move entirely up and down.

They have to go up and down together (not split).

![Screenshot_2022-10-01-22-02-42-36_fbcdf42ed509c3884e299b0f88be1eba (1)](https://user-images.githubusercontent.com/113377431/193426732-3bc86e43-7557-4264-89d9-817ee094a886.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Eliya-Manoj** [comment]
https://user-images.githubusercontent.com/90308888/214921521-94017472-f8dd-438f-8aa6-2b373ecaae84.mp4
