### ISSUE TITLE
instance

### ISSUE THREAD

**Issue by rzasharifi** [Bnyro/TranslateYou#121]
### Steps to reproduce

Hi. I downloaded Translate You Libre and the instance "https://libretranslate.de" is block in Iran. How can I find other instances for app?! 

### Expected behavior

Even with VPN I cannot translate my texts.

### Actual behavior

Failed to connect to the server

### Translate You version

2.7

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Instances can be found at https://github.com/LibreTranslate/LibreTranslate#mirrors. Bote that some of them require a paid API key.

I assume you're using the libre version of the app, I would recommend you to try the normal version as well 
(also available via IzzyOnDroid) as it supports 5 other translation engines than LibreTranslate too, you'll find something that works for you there.
