### ISSUE TITLE
Languages list on app's language

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#122]
### Describe your suggested feature

Right now languages list is shown in English only, regardless of the language selected. So if it possible, make it based on app's selected language
![](https://user-images.githubusercontent.com/113282550/209816142-83e5d8e9-4ae9-46bf-8d67-96182b7ea06d.png)

Also this one
![](https://user-images.githubusercontent.com/113282550/209816196-3021d0f0-fd87-4e2c-8a39-3ab5b7e3646a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible unfortunately. The name of the available languages is provided by the selected translation engine (an API call returns a list of available languages) which is using English only as possible language.
The only way I could think of is to translate the languages via the translation engine itself on app startup, but these results would be very unreliable depending on the engine as well as very bad for the app's startup performance.
