### ISSUE TITLE
Add audio support

### ISSUE THREAD

**Issue by coxde** [Bnyro/TranslateYou#126]
### Describe your suggested feature

For example, Lingva supports play audio (source and target), the audio are fetched from Google. Is there a way to play the audio in Translate You when using Lingva as API?

BTW thanks for your amazing apps!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't really know how to use the returned uint array returned by the lingva audio request properly, I'm open for help on that!

**Comment by gitterspec** [comment]
Perhaps it'd be helpful to look at the source of https://github.com/yaxarat/lingvaandroid which seems to implement this?
