### ISSUE TITLE
Transliteration of language into which something is translated

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#127]
### Describe your suggested feature

Right now transliteration approves only for language from which something is translated. I'd prefer to see transliteration of language into which something is translated.

### Other details

![](https://user-images.githubusercontent.com/113282550/210106599-2c57c689-f1dc-4cce-bf77-b168315e65ee.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I can't seem to find that in their API response, are you sure Lingva Translate supports it?
If so, I would be grateful if you can show me those in the API response.

**Comment by HotarunIchijou** [comment]
Unfortunately, I can't find this in their API

**Comment by Bnyro** [comment]
They probably don't support it yet then, I'm open for adding support as soon as it's available in their API.
