### ISSUE TITLE
Buttons in about page doesn't match Material You theme

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#128]
### Steps to reproduce

Open about page from action menu

### Expected behavior

Icons should match Material You theme color, I think

### Actual behavior

Instead this, icons are painted in purple color

### Translate You version

3.1

### Android version

Android 12

### Other details

![](https://user-images.githubusercontent.com/113282550/210158158-38032e10-32d4-441d-87d3-cfb9ace5737d.png)

Maybe it's not a flaw, but I think it should be painted in Material You theme color

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In fact it does use a theme color, just not the main accent color.
