### ISSUE TITLE
Functional and graphics improvements

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#13]
### Describe your suggested feature

My idea involves a reorganization of the bottom drawer.

To make room for the icons at the top it will be necessary to reduce the words ENG > ITA to two round flags: clicking on them will open a pop-up and make it easier to choose the desired language pair.

In the meantime we will have created space to accommodate the buttons that are now located (awkward to reach) at the top.

![Screenshot_2022-10-01-22-32-02-34_fbcdf42ed509c3884e299b0f88be1eba (1)](https://user-images.githubusercontent.com/113377431/193427322-7b8900c0-5dfd-4c99-8c50-dca93743dd81.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I've been thinking about it and in my opinion, the current design fits Material You better. When changing it as you suggested, the bottom would be very squeezed and I don't think it would look good to not have the languages centered at the bottom :)
