### ISSUE TITLE
Add option to disable automatic translation

### ISSUE THREAD

**Issue by gitabekaunt** [Bnyro/TranslateYou#146]
### Describe your suggested feature

Please allow disabling automatic translation that happens every x number of milliseconds

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
How else do you want to translate the text instead then?

**Comment by gitabekhaunt** [comment]
> How else do you want to translate the text instead then?

With a translaye button, please
