### ISSUE TITLE
Spaces deleted when deleting characters

### ISSUE THREAD

**Issue by gitabekaunt** [Bnyro/TranslateYou#147]
### Steps to reproduce

1. Type text
2. Delete some of it as automatic translation happens
3. Space is deleted behind the currently typed word

### Expected behavior

Spaces should not be deleted

### Actual behavior

When typing text and deleting characters, as automatic translation happens, the space behind the currently typed word is deleted sometimes

### Translate You version

3.3

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, at least the text is not trimmed from the side of Translate You. Might be an issue with the keyboard you're using.
