### ISSUE TITLE
ocr translator

### ISSUE THREAD

**Issue by Gamefire238** [Bnyro/TranslateYou#151]
### Describe your suggested feature

translate directly on the home screen by using the cursor to capture words and translate them, similarly (screen translate)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
What you describe is not OCR, translating selected text with the app is already possible.
