### ISSUE TITLE
Reverso engine for simultaneous translation

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#159]
### Describe your suggested feature

If it possible, add the Reverso engine for simultaneous translation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately that's not possible because Reverso uses language codes based on 3 characters (e.g. ger for German), while all the others use codes based on two characters (de for German).
