### ISSUE TITLE
UI translation

### ISSUE THREAD

**Issue by Ilithy** [Bnyro/TranslateYou#17]
### Describe your suggested feature

Hi;
_I would like to thank you first of all for this
excellent application._
Are we allowed to offer translations of the Translate You interface, and the app description files for the app stores? (for my part, in French)
Thank you.

### Other details

The proposal could simply be made by PR, 
With a concise and clear description of the files created/modified.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hey, 
Thanks for your positive feedback, I really appreciate that. And of course thank you for your interest in supporting the development :)

I'm planning to add the app to Weblate tomorrow, they offer a free tier for Foss projects (which I already use for two other Android apps :) ), I think translating via Weblate is more intuitive and fun than editing the strings.xml for most users that don't have any knowledge about Android development.

If you prefer to make a pr with the translated strings instead you can do that too if you want, I'm open for it, it's up to you.

Cheers

**Comment by Ilithy** [comment]
>Thanks for your positive feedback, I really appreciate that. And of course thank you for your interest in supporting the development :)

❤️

>I'm planning to add the app to Weblate tomorrow, they offer a free tier for Foss projects (which I already use for two other Android apps :) ), I think translating via Weblate is more intuitive and fun than editing the strings.xml for most users that don't have any knowledge about Android development.

This is a great idea, all the points you raise are right on.

>If you prefer to make a pr with the translated strings instead you can do that too if you want, I'm open for it, it's up to you.

Awesome and thanks, I'll make a PR (I've already translated everything), then I'll use Weblate (not to multiply the PR unnecessarily)
