### ISSUE TITLE
Inconvenient interface

### ISSUE THREAD

**Issue by Omegaplexx** [Bnyro/TranslateYou#194]
### Steps to reproduce

Hi! I really like your app, but the interface honestly needs some work.

For example, the context menu is too narrow to accommodate the last letter of the Russian translation of 'About'. ![Screenshot_20230313-031535_Translate_You~01](https://user-images.githubusercontent.com/95503207/224583856-b5fd1805-1b93-4e50-b5a6-b68637534d35.png)

The second (more general) problem is that the interface has a lot of empty space that could be reduced. The font size could be made smaller, and the text on the buttons could be shortened (for example, "Libre" instead of "LibreTranslate" and "Simply" instead of "SimplyTranslate").
![Picsart_23-03-20_05-22-53-403](https://user-images.githubusercontent.com/95503207/226233666-6e5b4783-33f0-47ac-9f5d-497f3d6d98e4.png)
As you can see in this screenshot, the bottom panel takes up about a third of the screen and contains useless elements, such as the "Detected language" field and a rather large "back to top" button (in this implementation it's more of a hindrance than a benefit).

![Picsart_23-03-20_05-26-22-746](https://user-images.githubusercontent.com/95503207/226233689-52da6976-ca4b-4d68-9c8e-2fba9ef157d9.png)
As a good example of interface realization I chose the DeepL app. Comparing to Translate You it's convenient to work with the translation of large texts due to the smaller font size. The elements of the bottom panel are smaller, and the language pair selection is moved to the upper part (header), so as not to overload the bottom panel.
DeepL is two-windowed. It's easy to edit the original and view the translation at the same time with that structure of the interface.

Third, it would be more convenient if the bottom panel were hidden when the keyboard is on.
![Picsart_23-03-20_06-12-09-469](https://user-images.githubusercontent.com/95503207/226238108-3518b0df-21c3-4449-bbf1-ce67f2696821.png)

Fourth, the settings screen has a huge panel on top with literally two functions. I think that it would be better to make a separate section in the settings with the configuration of each service separately.

### Expected behavior

Compact interface

### Actual behavior

Well... Not compact interface

### Translate You version

3.10

### Android version

Android 10

### Other details

I also want to note that Translate You has a lot more problems in landscape orientation than in portrait. In spite of this, I thank you a lot for a translating app that combines five services. Even though it is not very convenient yet, I hope that in the future Translate You will become my favorite translating app.

I relegated the Issue to a Bug Report, although I'm not entirely sure if this is a bug report or a feature suggestion. I'm sorry if I did something wrong.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Omegaplexx** [comment]
@Bnyro Thanks for the answer. Well, I'll get used to the interface then, but what about the horizontal orientation? Do I have to rotate the device on purpose to see the text field again?
![Screenshot_20230320-205327_Translate_You](https://user-images.githubusercontent.com/95503207/226425753-d669d4f9-0feb-455e-a6be-992f75855033.png)

**Comment by Bnyro** [comment]
Translate You doesn't support landscape mode properly for now. However, I wouldn't use translator apps in landscape mode in general as it's normal that the keyboard covers large parts of it. If you prefer so, I don't mind disabling landscape mode so that nobody accidentally gets into that situation.

**Comment by Omegaplexx** [comment]
@Bnyro, yeah, that's better than nothing. Thank you :)

**Comment by drogga** [comment]
Regarding the locked and unsupported orientation - that's unfortunate, I wish it worked and looked better in landscape (I forced it to check - basically unusable on phone, same as "monocles"), especially on 8+ inch tablets and all the Fold devices, with also minimal pop-up dialog/window when called from another app (text selection), just like the G., MS, Yandex and other "big name" ones and it didn't constantly fail to translate from any of the engines (shows a toast msg. and when you see it too many times in a short period of time, it gets really annoying), there's also no Live camera translation functionality and it doesn't use the native txt selection options, but a few predefined limited ones, that don't even respect the dark theme and are in white, which makes unreliable and unfortunately won't replace them for me at least - sorry.
