### ISSUE TITLE
IzzyOnDroid inclusion

### ISSUE THREAD

**Issue by Bnyro** [Bnyro/TranslateYou#2]

**Comment by Bnyro** [comment]
Hey @IzzySoft, sorry to disturb you once again.

I would be very pleased if you would consider adding TranslateYou to your repo :)
The `fastlane` structure should already be set up completely (at least I hope there's no misconfiguration this time 😂)
I'd start adding changelogs too with the next release so it'd be nice if you could pull them too then.

Cheers
Bnyro

**Comment by IzzySoft** [comment]
Hi @Bnyro and apologies for my delayed answer (I was on vacation). Just added your app now (will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.bnyro.translate) with the next sync around 6 pm UTC), be welcome picking [a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there.

Fastlane is working fine, thanks to that. I've already prepared it for per-release changelogs which you wanted to add for the next release, so they should be picked up then. If you want to improve your "full description", find some [formatting hints here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane).

**Comment by Bnyro** [comment]
Hey @IzzySoft,
Thank you for adding Translate You to your repo!
Thank you for the hint with the `full_description.txt`, I struggled a bit when setting it up, I'll definitely have a look at your guidelines for that later, thanks :)

I got one question, I'm planning to add support for [Lingva Translate](https://github.com/thedaviddelta/lingva-translate), which is using the Google Translator internally. That will result in `NonFreeNet` being added as anti feature, right?

PS: No worries about the delay, hope you enjoyed your "digital detox", that's probably something I should do too ;)

**Comment by Bnyro** [comment]
> Yes, that would raise `NonFreeNet`. Hopefully you can achieve that without any proprietary libraries, otherwise it would at least also result in NonFreeDep (or even prevent inclusion/updates if those non-free parts sum up too much).
>
Okay, thank you for the answer! There won't be a need to use non-free libraries, otherwise I wouldn't even consider adding support for it :)
Lingva has a public REST API that can just be fetched very easily without much effort.
However, I'm still not sure whether adding it is worth the anti-feature, so I might start a discussion about it to figure out what others think about it.

> And yeah, it was a partial detox (I had my phone with me for reading news – and running around mapping for OSM using StreetComplete. Cyprus needed a lot of updates, some details were outdated for more than 5 years already. Was fun doing, and got me moving a lot instead of sitting at my desk see_no_evil
>
Haha, obviously there are not as many open source fanatics there as in Germany, no matter where I go here most things are mapped pretty well ;)
But making vacation for updating the maps of a country seems a bit too demanding for relaxing completely, doesn't it? 😂

**Comment by IzzySoft** [comment]
> I'm still not sure whether adding it is worth the anti-feature

alternative options:

* make it an addon to be installed separately (e.g. a separate APK which, if present, is detected by the main app and "integrated"). That usually would mean `NonFreeAdd` – but I meanwhile tend to be lenient if it's not "massively promoted" from inside the main app – i.e. no popups etc asking the user to install it, just silently accepting the presence if given). Then `NonFreeNet` would be applied to the addon, not to the main app.
* use build flavors and make two different apps. If they come with dedicated ApplicaionIds (e.g. the new one having a `.gtrans` suffix) I could host both – and again `NonFreeNet` would only apply to the new one.

> But making vacation for updating the maps of a country seems a bit too demanding for relaxing completely, doesn't it?

If you look at it like that, yes. I did it differently: I dedicated about 3 hours on 3 or 4 days to explore some surroundings I didn't check thoroughly before, and watched what StreetComplete was asking along the way. Found some interesting places that way I even could point out later to other vacationers (when our shuttle passed nearby on the way to the airport). That's the nice thing with StreetComplete: you enjoy the surroundings – and if you feel like, you solve some quests with it. You should give it a try :smiley:

Oh, and I learned new stuff using SC as well. For example, on a traffic light I was asked whether it supports haptic feedback for blind people. Never knew such thing exists – but indeed there it was, hidden in plain sight! There's one such traffic light near my home, and when passing it in the evening you have to look straight into the sun, having a hard time seeing when it switches green (the traffic light, not the sun :rofl:). No longer: now I simply put my hand on the knob and wait until it vibrates, then I walk :star_struck:

**Comment by Bnyro** [comment]
> alternative options:
>     * use build flavors and make two different apps. If they come with dedicated ApplicaionIds (e.g. the new one having a `.gtrans` suffix) I could host both – and again `NonFreeNet` would only apply to the new one.
> 
Yes, that's a good idea, it would probably be the easiest way for me and would head the choice over to the users about which version they want to use.
I will inform you as soon as it requires further steps, just to bring you back to sitting at your desk :)

> If you look at it like that, yes. I did it differently: I dedicated about 3 hours on 3 or 4 days to explore some surroundings I didn't check thoroughly before, and watched what StreetComplete was asking along the way. Found some interesting places that way I even could point out later to other vacationers (when our shuttle passed nearby on the way to the airport). That's the nice thing with StreetComplete: you enjoy the surroundings – and if you feel like, you solve some quests with it. You should give it a try
> 
Haha, doesn't sound too bad, I will consider it when being in vacation the next time, definitely a innovative way for exploring countries or cities one hasn't been to yet by having some fun in the meanwhile :)
(And it's probably good for the ELO to complete quests :laughing: )

> Oh, and I learned new stuff using SC as well. For example, on a traffic light I was asked whether it supports haptic feedback for blind people. Never knew such thing exists – but indeed there it was, hidden in plain sight! There's one such traffic light near my home, and when passing it in the evening you have to look straight into the sun, having a hard time seeing when it switches green (the traffic light, not the sun). No longer: now I simply put my hand on the knob and wait until it vibrates, then I walk
>
Indeed, that's interesting. The question is just who needs such information when using OpenStreetMap in the end, but maybe people choose their routes depending on whether the traffic lights support haptic feedback, who knows :rofl:

**Comment by Bnyro** [comment]
I updated the `full_description.txt` to use some proper formatting now and therefore close the issue for the moment, the Lingva Translate stuff will be part of a separate issue :)

**Comment by IzzySoft** [comment]
Keep in mind that a different ApplicationId also means no cross-updates – so if there are any settings or user-data, consider an export/import feature to transfer them between the two.

> The question is just who needs such information when using OpenStreetMap

Visually impaired people? You don't think there's no way for them to use that, do you? There are tons of specific interfaces using OSM data – for cyclists, vegetarians/vegans, wheelchair – and also visually impaired people. Just check the OSM wiki to find out. You can e.g. start with the [software categories](https://wiki.openstreetmap.org/wiki/Category:Software) and find the [OSM Direction tool for Visually Impaired](https://wiki.openstreetmap.org/wiki/OSM_Direction_tool_for_Visually_Impaired), but also many more.

**Comment by Bnyro** [comment]
> Visually impaired people? You don't think there's no way for them to use that, do you? There are tons of specific interfaces using OSM data – for cyclists, vegetarians/vegans, wheelchair – and also visually impaired people. Just check the OSM wiki to find out. You can e.g. start with the [software categories](https://wiki.openstreetmap.org/wiki/Category:Software) and find the [OSM Direction tool for Visually Impaired](https://wiki.openstreetmap.org/wiki/OSM_Direction_tool_for_Visually_Impaired), but also many more.
>
Oh, I apologize, I wasn't aware that OSM offers support for that, it seemed kinda unrealistic to me that visually impaired people would be able to use OSM, I just couldn't imagine it.
Sure, you're absolutely right, it makes sense to help them by providing such details in the map. I will definitely give it a try in the future, that's really a honourable free time activity (even if most entries you add to the map are not only specifically for people that have such a hard life)!

**Comment by Bnyro** [comment]
> Keep in mind that a different ApplicationId also means no cross-updates – so if there are any settings or user-data, consider an export/import feature to transfer them between the two.
> 
Yes, that makes sense, I will remember to do so if there ever will be something similar, thanks for your effort in helping me!

**Comment by IzzySoft** [comment]
> even if most entries you add to the map are not only specifically

Once you've used StreetComplete for a while you will have learned many interesting things – including what kind of people you might be helping with providing details. It's really fascinating. In terms of handicaps, there are also such things like wheelchair specific markings (a la "is there a ramp next to that stairway", or "is this place accessible with a wheelchair"), or for the elderly ("does this stairway have a hand rail", "how many steps does it have"), (not only) for women at night ("is this street lighted")… And you start noticing things you've passed multiple times without looking at, even next to your own door :see_no_evil:

**Comment by Bnyro** [comment]
I just have been starting with it in my home town, you're right, some quests are about things I've never thought about before, it's really funny to "discover" your home town from a new perspective. Unfortunately some quests are also kinda repetitive, for example determining which kind of houses are located on certain places or for example the flooring.
However, thanks for making me familiar with it, I'm working on finishing my quests here ;)

**Comment by IzzySoft** [comment]
It indeed is fun! And has a nice side-effect for "office sitters" like me: I suddenly find a reason for a walk. Though with the time, my surroundings are already "processed". Luckily, new versions of StreetComplete often bring new types of quests, so after a while one can "scan" the same area again. Glad you enjoy it, too!

PS: One of my "hated repetitive quests" is: "how many steps does this stairway have" (which I usually skip if there are too many and I'm not walking it myself). Also, some quest types take you a while to understand – I still struggle to define "which way is up" with stairs. Always looked to me like "left or right", which would be stupid. Guess the arrows there mean: "from where you stand, is it up or down?". So even things to discover in the app itself. And the devs are quite active, as is their community.

**Comment by Bnyro** [comment]
> It indeed is fun! And has a nice side-effect for "office sitters" like me: I suddenly find a reason for a walk.
> 
Agree, I still remember when so many people have been behaving the same way, but for Pokemon Go and not StreetComplete. Maybe SC is just the better version of it :rofl:
> PS: One of my "hated repetitive quests" is: "how many steps does this stairway have" (which I usually skip if there are too many and I'm not walking it myself). Also, some quest types take you a while to understand – I still struggle to define "which way is up" with stairs. Always looked to me like "left or right", which would be stupid. Guess the arrows there mean: "from where you stand, is it up or down?". So even things to discover in the app itself. 
>
Haha, had that "up/down"-quests too already a few times, luckily the stair-counting quest noy yet, I would probably skip it then :)
>And the devs are quite active, as is their community.
>
That's nice, indeed, is there any official place for the community to meet, like a Matrix room, you're aware of? :)
