### ISSUE TITLE
Missing translation on LibreTranslate

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#20]
### Steps to reproduce

![Screenshot_2022-10-08-07-49-22-14_23ac93267c0fe78a3ab35e3ff4008864 (1)](https://user-images.githubusercontent.com/113377431/194691416-2ec41bd0-262a-4179-b935-f74ba7a9f621.jpg)

When I paste a text in pasteboard translation doesn't run. 

### Expected behavior

TY 1.4 normal version
Translation Provider -----> libretranslate.de
Android 12

### Actual behavior

See details.

### LibreTube version

1.4

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ilithy** [comment]
I noticed this too, however, with lingva selected as the translation engine,
the pasted text is translated instantly.

app: Translate You version 1.4
device: Pixel 6 pro
OS: Grapheneos - Android 13

**Comment by Ilithy** [comment]
>Unfortunately also with Lingva engine it happens.

On my side Lingva works perfectly

>I'm gonna debug it and try to find out what's going on :)

Thanks

**Comment by Bnyro** [comment]
Found the issue, should be fixed now :)
But it may make sense to add a button somewhere to allow users to fetch the translation manually, not sure where to put it though

**Comment by Ilithy** [comment]
> No new buttons: press and hold "+" button runs translation again.

Good idea, but this behavior should surely be noted somewhere.

Otherwise a smaller button above the "+" button could do this easily too _(aside, an option to switch these buttons to the left side would be nice, for lefties <3)_
