### ISSUE TITLE
Translate content directly in other apps

### ISSUE THREAD

**Issue by zoroya1** [Bnyro/TranslateYou#200]
### Describe your suggested feature

So, currently in Translatw you, when user wants to translate a word, he has to select the word and select translate pop up and it opens translate you app.
  It will be helpful if app can have an overlay or small window on the app which is alredy open...
I hope i descirbed it correctly

How will user get benefit ?
 I think this option can eliminate need of opening a new app besides currently open ebook or webpage
User can see the translated word can can close the pop up of translate you, get beck to their work.

### Other details

It can be just like this app : [Instalate](https://gitlab.com/concept1tech/instalate)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This is not planned, see #152
