### ISSUE TITLE
Auto detect language with public LibreTranslate instance not working

### ISSUE THREAD

**Issue by Arne19** [Bnyro/TranslateYou#202]
### Steps to reproduce

1. go to settings and set https://translate.monocles.de as LibreTranslate instance
2. go back where auto detect is activated
3. Write a sentence in German

### Expected behavior

The text will be auto detected as German and translated to English

### Actual behavior

The Text is not translated but it's endlessly loading

### Translate You version

Directly from source / 3.10

### Android version

13

### Other details

Hi, first of all, thanks for your apps!
I'm just having this issue with the monocles LibreTranslate instance and I'm not sure what's the reason, because the auto detection does work in the web interface. Here's the log:

I/okhttp.OkHttpClient: {"detectedLanguage":{"confidence":95.0,"language":"pt"},"translatedText":"Hallo, ich that Spargel"}
I/okhttp.OkHttpClient: <-- END HTTP (100-byte body)
E/error: Unexpected JSON token at offset 34: Unexpected symbol '.' in numeric literal at path: $.detectedLanguage.confidence
JSON input: {"detectedLanguage":{"confidence":95.0,"language":"pt"},"translatedText":"Hallo, ich that Spargel"}

When manually choosing a language inside Trasnlate You it works. Both, building the app from source or running the latest f-droid version seem to have this problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for reporting with the error log, the issue will be fixed within the next release!
