### ISSUE TITLE
Standard Release

### ISSUE THREAD

**Issue by xmha97** [Bnyro/TranslateYou#206]
### Describe your suggested feature

Please add the "app-standard-release.apk" to new versions:

![Screenshot_2023-03-30-13-52-16-132_com github android](https://user-images.githubusercontent.com/23485114/228807315-3efe84c7-268a-4487-8bd3-c688cfad2cee.jpg)

![Screenshot_2023-03-30-13-55-28-698_com.github.android.jpg](https://user-images.githubusercontent.com/23485114/228807982-f639a5fc-9af7-439b-becc-93449fccdf5f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Since 3.8, the libre version contains all the features from the standard version.

**Comment by xmha97** [comment]
Ok, thanks you.
