### ISSUE TITLE
App redesign

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#210]
### Describe your suggested feature

Hi @Bnyro, I've been thinking and I've decided that the current design looks a bit dated. So I've tried to made an app redesign. Here's a [link](https://www.figma.com/file/1CJX1mPyAq6oGS7iGEj4Kn/Translate-You?node-id=0%3A1&t=wq05pjaQlxmrJVxZ-1) to this. I hope you look for this, change this, if it necessary, and make an app redesign.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for your efforts, I really like your drafts, especially the design of the new language selection menu.
I can't promise I'll find time for it too soon, but I'll definitely implement some of the suggestion in the coming time :)

**Comment by HotarunIchijou** [comment]
Thanks for your reply. It seems to me that the language selection menu needs to be enhanced a bit, mostly indents, so I'll try to work on it

**Comment by Bnyro** [comment]
Could you please share an SVG version of the image with the three stars that you used next to "Detect language"? I haven't been able to find something similar.

**Comment by HotarunIchijou** [comment]
Sure, it's [here](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aauto_awesome%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)

**Comment by Bnyro** [comment]
Great, thank you!

**Comment by HotarunIchijou** [comment]
> In the second image, I didn't see any real changes apart from the history button added to the top bar, however I don't see a reason for that as it can be accessed via the three dot menu next to it

You right, it doesn't contains any real changes, exclude sheetless screen (in the original design there's a sheet around text)
Also I forget to mention that translated text also appears on second image concept, with the same colors and horizontal divider, that the third one. Also color of translate buttons text are different (original app have the primary Material You color, when my prototype is not). Also divider can be a progressbar, so it shouldn't change in size. 
History button needs more actions for accessing this (1 vs 2 actions) so I can't see the reason why it should be hidden in the  menu.


> I think that the third suggestion (replacing the language selector with a floating action button after a translation has finished would probably make everything less user friendly

Maybe you right. I've inspired by Google Translate and made something simmilar with this, but it's final translate after all

**Comment by HotarunIchijou** [comment]
I looked at the new version, and you barely made a difference.  I hope that the next versions will contain more new features and ideas from my layout.

**Comment by HotarunIchijou** [comment]
Not really. I mean, you mostly made language choose redesign, and it's almost perfectly, exclude some things. At first, you used wrong language pick color (it's primary, while in my layout it's not). At second,  status bar and navbar doesn't follow background color (see screenshot below)![](https://user-images.githubusercontent.com/113282550/229898155-63b0554f-9536-4fbc-81ef-63ad573bcae7.png)
At third (I don't make this thing in my layout, but anyway) titlebar doesn't fold and doesn't make background, like in screenshot below ![](https://user-images.githubusercontent.com/113282550/229899073-d5509e62-b6d4-4d6a-9f05-23b9d4649152.png)
So this claim not to you because I didn't realize this by myself.


The rest that you changed is the buttons, but also not as I wanted. Please, check again my figma layout carefully, with checking comments and launching prototype

**Comment by Bnyro** [comment]
Sorry, I'm not really familiar with Figma myself and thus only looked at the 5 initial pictures showing up when opening the link you have added in the issue description.
I see the issues you described above and will attempt to partially fix them from time to time, however I feel like the current changes are good enough for the moment.
Thanks for your patience though.

**Comment by HotarunIchijou** [comment]
Don't worry about that. You just need to click to element that you're interested in and conside it. Also you can get xml code of any element by going to inspect in the right menu. I can take out the colors and write their Material You names for better clarity, if you want so.

Also you can watch the basic presentation to see the basic UX by pressing on the play button in top-right corner or by pressing hotkey (ctrl+alt+enter)

I hope that this information will be helpful for you
