### ISSUE TITLE
Save translations as favorites

### ISSUE THREAD

**Issue by fellinir** [Bnyro/TranslateYou#215]
### Describe your suggested feature

Other then history, it would be nice to have the possibility to save done translations as favorites.

### Example from DeepL app

![Screenshot_20230405-215440_DeepL](https://user-images.githubusercontent.com/92597054/230475618-301a10d7-a4b6-4f4b-bfa5-f3dfdc0e1fc9.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however I don't see any viable reason for adding support for saving favorite translations. Wouldn't it make more sense to provide a search feature in the history instead?
