### ISSUE TITLE
Add headerbar in the simultaneous translation menu

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#219]
### Describe your suggested feature

I was thinking for a long time what's wrong with simultaneous translation menu and I finally understood: there's no headerbar. So please add it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You mean the dialog?

**Comment by HotarunIchijou** [comment]
Yes
