### ISSUE TITLE
Settings redesign

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#225]
### Describe your suggested feature

![](https://user-images.githubusercontent.com/113282550/232322243-dbd9e32a-7100-4f21-88cf-a7d7b9d26faf.png)
I think it would be better if this things were a menu items, not icons at the top

![](https://user-images.githubusercontent.com/113282550/232322315-ae667e93-6025-4b02-99ae-b0015eedbe24.png)
Also it would be a little nicer if a menus looked ike this

![Screenshot_20230416-181426_Translate_You](https://user-images.githubusercontent.com/113282550/232322496-f28a8557-a1d4-4061-92ec-af64f31fee48.png)
Don't know what's the purpose of this elements arrangement, but mostly md3 apps (even your) locates title below the back button

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however
1. The top bar we're using is designed as per the MD3 guidelines, see <m3.material.io>.
2. The appearance settings are located at the top right because they're not releated/different to the other settings.

Thus, no changes planned here.
