### ISSUE TITLE
SimplyTranslate: random selection and fetching from multiple instances

### ISSUE THREAD

**Issue by gitterspec** [Bnyro/TranslateYou#228]
### Describe your suggested feature

Instances are often down so this would make SimplyTranslate more usable as a practical option. The SimplyTranslate Mobile app (https://f-droid.org/en/packages/com.simplytranslate_mobile/) has a good implementation of this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however I currently don't plan to add something similar, mostly because it causes unnecessary server traffic and users should be aware of which instance they're using imo since they should trust it to be privacy friendly.
