### ISSUE TITLE
Option to show pronounciation from Lingva

### ISSUE THREAD

**Issue by gitterspec** [Bnyro/TranslateYou#235]
### Describe your suggested feature

Would be great to have this as an option. Indispensable for certain languages that don't use phonetic scripts - otherwise, would have no idea how to speak the translation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
If available, the pronunciation is already shown in the additional info component, it's called "Transliteration"
