### ISSUE TITLE
Translate buttons redesign

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#239]
### Describe your suggested feature

I think it should be a little bit larger than the current one and should have **fixed size**. Also long language names, like "chinese (simplified)"  should fit on 2 lines and the whole name of language name should be visible, instead of current one. It also would be nice if you add an animation of language swapping

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
A fixed button size is not a good idea because that would cause accessibility issues when people increase or decrease the font size manually in the Android accessibility settings.

I don't plan to add an animation for language swapping.
