### ISSUE TITLE
Simultaneous translation

### ISSUE THREAD

**Issue by Ilithy** [Bnyro/TranslateYou#24]
### Describe your suggested feature

I don't know if this is feasible, but it would be fantastic if, during a translation, Translate You could make the translation request to all these engines at the same time.
Each translation engine would display its result in a separate tab
This would make it possible to check the translations by the different engines very quickly and easily, which would be extremely appreciable _(especially if other engines come to join TY)_.

Thanks a lot

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ilithy** [comment]
>That's not possible with the current way of how Translate You works, but it wouldn't be too hard to implement :)

That would be really awesome 😍, thank you for considering it 🙏 (even if it doesn't included).

>How do you imagine the different tabs to be like (where, how to switch between them)?

I was thinking about small buttons (each engine having its own button, visible if you activate the translation engine in the settings) in the system accent color (like the "+" button) to install
at this place (screenshot), it would switch the view from one translation engine to another (this would be, for me, the most pleasant and convenient, we can easily change/change the engine, to compare them).

![Screenshot_20221009-184235__01](https://user-images.githubusercontent.com/36798218/194769905-3454acf3-f6ed-4d3f-8c2d-8843a0d76bd0.jpg)

>Should the option for it be just a switch in the settings?

Exactly, for each translation engine

>The different engines support different languages, therefore there'll be a need to work around that somehow

Indeed, simply displaying a message, "languages not supported by this translation engine, sorry" would not be possible? 

>What I could also imagine instead is a button, for example next to the translated text, clicking it opens a dialog that allows to choose to fetch the translation from another supported engine, which would be better/easier in terms of UI I think.

In my opinion it would be less convenient, because in my method, we can change engines quickly, and compare the work of different engines, while your method forces _(well, I think)_ to systematically send a request at each change of translation engine. 
But I could be totally wrong...

Thank you very much ❤️

**Comment by Ilithy** [comment]
for a slightly more precise idea of the design I'm thinking of for the (open tab) buttons mentioned in my previous comment. here is an example very close to my idea:

![Screenshot_20221009-205952](https://user-images.githubusercontent.com/36798218/194775009-1740ab15-f1d6-4870-89e7-5262f3cf6da3.jpg)
_(screenshot of the Neo Store app)_

But displayed at the bottom, not at the top (more accessible)

**Comment by Bnyro** [comment]
I decided to set this as the major goal for version 2.0 as it'll require rewriting some core parts of the code and also some work spent on UI stuff that'll probably transform parts of the app revolutionary :wink:

Before that I'm gonna have a look at some other translation engines to add so that the feature will be really useful then when it's being rolled out :)

PS: I like the idea with the chip group, we'll just need to figure out how it'll look the best in TY in the end. Apart from that I'll need to find the best way to make it work well with new translation engines too without much additional work for each engine, so there's some work to do obviously :joy:

**Comment by Ilithy** [comment]
> I decided to set this as the major goal for version 2.0 as it'll require rewriting some core parts of the code and also some work spent on UI stuff that'll probably transform parts of the app revolutionary 😉

🥳🙏 Thank you very much, this is going to take a lot of work, thank you for putting it on your to-do list.
Indeed this will make Translate You the most effective translation app on Android by far.
_I think it may be necessary to modify other parts, so that it is really practical, like the "+" button which should surely become smaller (maybe)._

> Before that I'm gonna have a look at some other translation engines to add so that the feature will be really useful then when it's being rolled out :)

It's clever. I just added a request to add Deepl (which is excellent, and has an interesting free version API)
If it doesn't bother me, I'll make other requests for alternative translation engines.

> I like the idea with the chip group, we'll just need to figure out how it'll look the best in TY in the end.

I understand, these are preliminary ideas: it could be like in the example, with less padding and a selectable order of appearance 

>Apart from that I'll need to find the best way to make it work well with new translation engines too without much additional work for each engine, so there's some work to do obviously

yes, I get it, this part of the story is going to be difficult for me ^_*

**Comment by Bnyro** [comment]
Short update on that:

1. During the last few updates, as a side effect, I've been pretty much doing all the refactoring and rewriting to make it possible to include this feature in the future.
2. Now the bad part: as I won't be at home for a week starting this Saturday, I can't promise I'll find time to work on it before as I still have to maintain some other stuff and also do some IRL stuff to before my trip starts :)

So, just wanted to quickly inform you that I didn't forget it yet :)

**Comment by Ilithy** [comment]
Thank you very much for this information and the follow-up on this request _(but also on the rest)_, you have already done a lot of work, and TY is already one of the best apps in this category (it may already be the best), thank you for that.

I appreciate you keeping this feature in mind, it's already a lot, thank you.

I hope your trip is going well, take care of yourself(Modifié)

**Comment by Ilithy** [comment]
Wow It was really very _very_ fast, infinitely more than I thought, thank you very much 👏
