### ISSUE TITLE
Support for opening deeplinks 

### ISSUE THREAD

**Issue by soymadip** [Bnyro/TranslateYou#240]
### Describe your suggested feature

If app can open deeplinks ( specially google translaye's translate.google.com), other apps can automatically use this app's translation service.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Do you mean only opening the app automatically when the URL is called or to automatically insert the text into the app? Could you please provide example links?

**Comment by soymadip** [comment]
> Do you mean only opening the app automatically when the URL is called or to automatically insert the text into the app? Could you please provide example links? 

Yeah, specially 'automatically insert the text into app'

I have no coding experience so i don't know the main process, but i am leaving a screen record demonstrating the process i tried with [moon reader ](https://play.google.com/store/apps/details?id=com.flyersoft.moonreader) :- 
https://github.com/Bnyro/TranslateYou/assets/84225810/acf1ada4-3cf4-4e29-8633-fc325d02f6fd
