### ISSUE TITLE
Bergamot API support

### ISSUE THREAD

**Issue by Terkyz** [Bnyro/TranslateYou#241]
### General informations
The Bergamot Project Consortium is coordinated by the University of Edinburgh with partners Charles University in Prague, the University of Sheffield, University of Tartu, and [Mozilla](https://blog.mozilla.org/en/mozilla/local-translation-add-on-project-bergamot/). That said, for me as a user I can use Bergamot to perform translations directly from the browser offline, and there are already several projects using this, such as [Firefox Translations](https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/) and [Linguistic](https://addons.mozilla.org/en-US/firefox/addon/linguist-translator/), the last one being a non-Mozilla project.

Honestly I am not sure but it should not need an API for translations, but what I am sure is that it is an [open source project](https://github.com/browsermt/bergamot-translator), what I do not know is if it is possible to port this to a mobile app...

My apologies if this request is a bit useless, but I don't know anything about APIs or how to integrate them.

### API basic informations

- [ ] This translation engine requires a registered account.
- [ ] This translation engine requires an free api key.
- [ ] This translation engine requires an paid api key.

### Acknowledgements

- [X] I have searched the existing requests and this is a new ticket, **NOT** a duplicate or related to another open or closed request.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately the library seems to be written in C++/WASM and doesn't provide any bindings to become used with Java or Kotlin which TranslateYou is using. I tried to find a public internet API we could use, but there doesn't seem to be any either.
