### ISSUE TITLE
Predictive back gesture support

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#242]
### Describe your suggested feature

https://developer.android.com/guide/navigation/predictive-back-gesture

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned currently since Jetpack Compose does not yet support it natively.
