### ISSUE TITLE
Backup Function

### ISSUE THREAD

**Issue by IM71** [Bnyro/TranslateYou#249]
### Describe your suggested feature

Function like "Save Words" and have ability to be export to device storage.
Then when switching device, the saved words can be carry around and import.
Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please explain why that would be useful? Can't you already use the history for that?

**Comment by Bnyro** [comment]
Closing as currently not planned.

**Comment by IM71** [comment]
> Could you please explain why that would be useful? Can't you already use the history for that?

Hi sir, sorry I didn't get the notice back then.

The reason I want this feature it's because I'm not english native speaker, so I'd like to preserve those words that are special or interesting, I'd like to carry these words when switching phone (usually, I use a phone for 4 years), so that's a lot of words accumulated in translation app.

**Comment by quazar-omega** [comment]
I agree with @IM71, I think it is rather important to be able to keep this data, not being able to transfer it, means that you lose on a load of past translations that could be useful to you again, be it practically, or simply to look back on what you used to translate in the past
