### ISSUE TITLE
Communication error with the server

### ISSUE THREAD

**Issue by M0lyk** [Bnyro/TranslateYou#250]
### Steps to reproduce

Installed TranslateYou for first time, v5.2 on FDroid, Pixel 6a on Android 13

### Expected behavior

Get a translation in another language when I've entered a text to be translated

### Actual behavior

I never got any translations.

I tested with the 6 built-in translation engines

I get an error notification bubble which tells me that communication with the server has failed.

I don't use a VPN and I've tested with several DNS in my mobile settings. I'm connected to my WiFi.

![Screenshot_20230525-185952_Translate You](https://github.com/Bnyro/TranslateYou/assets/1733940/56dedc45-67db-4a4a-a3b5-bf684b269998)

### Translate You version

5.2

### Android version

custom rom Evolution X 7.9, may 2023, Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Seems like the pre-selected LibreTranslate instance doesn't work currently.
Go to the settings (three dots menu) and either enter a difference instance URL for LibreTranslate or select a different translation engine (e.g. Lingva).

**Comment by Bnyro** [comment]
Can't reproduce. Can you reach the instances via your browser?

**Comment by Bnyro** [comment]
And did you make sure to select some different languages?

**Comment by M0lyk** [comment]
Surprising result, I didn't change anything, and suddenly the application started working properly, except with Deepl on which I don't have an account and API, but for the rest it works fine. I don't know what happened.

**Comment by Bnyro** [comment]
Maybe a temporary internet issue? :thinking:
Anyways, problem solved :)

**Comment by Bnyro** [comment]
Likely, you might just want to clear the app's cache next time?

**Comment by exalented** [comment]
> Likely, you might just want to clear the app's cache next time?

This does not solve the problem
