### ISSUE TITLE
Request to support Image Translation for Santali language

### ISSUE THREAD

**Issue by Prasanta-Hembram** [Bnyro/TranslateYou#255]
### Describe your suggested feature

Hi, Translation from Image is possible for Santali language using the tessdata provided by [Indic-Ocr](https://github.com/indic-ocr) -- https://github.com/indic-ocr/tessdata/tree/master/sat . Don't know which version they use but should work!!.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We're currently using https://github.com/adaptech-cz/Tesseract4Android and there are no plans to add additional libraries / support.
