### ISSUE TITLE
Request for adding more machine translation alternatives

### ISSUE THREAD

**Issue by Prasanta-Hembram** [Bnyro/TranslateYou#259]
### Description

Adding these machine translation alternatives will increase the number of languages supported for machine translation up to [200](https://ai.facebook.com/research/no-language-left-behind/), including low-resource languages such as Asturian and Luganda. These online hosted machine translation service providers use NLLB (both Glosbe and MinT) and MarianNMT (only Glosbe) models.

Add more machine translation alternatives:
1. https://translate.glosbe.com (Glosbe Translate hosted by Glosbe)
2. https://translate.wmcloud.org/ (MinT Machine translation hosted by Wikimedia Foundation) - API spec (https://translate.wmcloud.org/api/spec)

I think this may be the first time it will be used in any app if these are included.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Both seem possible to add and very promising, thank you for the suggestion!
I'll try my luck with them in the next days :)

**Comment by Prasanta-Hembram** [comment]
Thank you for adding these machine translation alternatives.🙏🙏
