### ISSUE TITLE
Chinese Translations Incorrect

### ISSUE THREAD

**Issue by fjpereny** [Bnyro/TranslateYou#262]
### Steps to reproduce

1. Launch App
2. Select Auto "From" 
3. Select Chinese "To"

Type "hello"

### Expected behavior

Should get 你好 (ni hao)

### Actual behavior

Got 背景 (means background)

### Translate You version

5.2

### Android version

Huawei Harmony OS 3.0.0

### Other details

Some Chinese translations are way off, even extremely simple ones come back with weird results.  Others are close but still wrong.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please edit them here: https://hosted.weblate.org/projects/you-apps/translate-you/
