### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [Bnyro/TranslateYou#265]
### Steps to reproduce

https://monitor.f-droid.org/builds/log/com.bnyro.translate/33#site-footer

[trans.zip](https://github.com/Bnyro/TranslateYou/files/11645179/trans.zip)

Looks like the jdk is different but there may be other problems. What jdk do you use to build the release apk?

### Expected behavior

_

### Actual behavior

_

### Translate You version

_

### Android version

_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Oh well, it seems like I had been using the jbr 17 (17.0.6) instead of jdk 17 (17.0.7) when building the release. I guess that's the issue?

**Comment by linsui** [comment]
Maybe. Could you rebuild the apk with jdk 17 or 11?

**Comment by Bnyro** [comment]
Sure:
[ty-jdk11.zip](https://github.com/Bnyro/TranslateYou/files/11645219/ty-jdk11.zip)
[ty-jdk17.zip](https://github.com/Bnyro/TranslateYou/files/11645220/ty-jdk17.zip)

**Comment by linsui** [comment]
The jdk 11 apk is the same as our build with jdk 11. But the jdk 17 apk is different with our build with jdk 17 and 11. I guess it's because both jdk is installed in your environment and jdk 11 is also used by gradle when you want to use jdk 17. Which jdk will you use for release build?

**Comment by Bnyro** [comment]
I would like to bump the app to using Java 17 soon, so I guess it makes sense to go with JDK 17 now?

**Comment by linsui** [comment]
Could you remove other jdk versions and rebuild the apk with jdk 17, this hopefully can fix the problem. Or try bumping [this](https://github.com/Bnyro/TranslateYou/blob/master/app/build.gradle#L50).

**Comment by Bnyro** [comment]
> Could you remove other jdk versions and rebuild the apk with jdk 17, this hopefully can fix the problem. Or try bumping [this](https://github.com/Bnyro/TranslateYou/blob/master/app/build.gradle#L50).
>
I've bumped the AGP, and Java version now. Release build based of https://github.com/Bnyro/TranslateYou/commit/4e5e0dd4ed062aa2866c81da9872d3e05a6311b7:
[ty-jdk17-java17.zip](https://github.com/Bnyro/TranslateYou/files/11645391/ty-jdk17-java17.zip)

**Comment by linsui** [comment]
It's not reproducible but looks like it's similiar to a known bug. 
[train.zip](https://github.com/Bnyro/TranslateYou/files/11645442/train.zip)
https://issuetracker.google.com/issues/281825213 Any idea?

**Comment by Bnyro** [comment]
Not really, the app doesn't have `generateLocaleConfig` set to true so it shouldn't be the same issue

**Comment by linsui** [comment]
Looks like the different classes correspond to https://github.com/Bnyro/TranslateYou/blob/900d5be9ca109b276474c75e38f135b382df4b02/app/src/main/java/com/bnyro/translate/util/LocaleHelper.kt#L36 and https://github.com/Bnyro/TranslateYou/blob/900d5be9ca109b276474c75e38f135b382df4b02/app/src/main/java/com/bnyro/translate/api/gl/GlEngine.kt#L45. Looks like we build the apks from different commits. Your apk doesn't have https://github.com/Bnyro/TranslateYou/commit/b7567faff5cea3598e512f7a7f4c2f50784a72b1 and https://github.com/Bnyro/TranslateYou/commit/cf32e1ac1049a414fa353aa9221ef798d3148712.

**Comment by Bnyro** [comment]
Oh, I likely forgot to run `git pull`, totally my bad!
New one: [ty.zip](https://github.com/Bnyro/TranslateYou/files/11646581/ty.zip)

**Comment by Bnyro** [comment]
Next attempt: built from https://github.com/Bnyro/TranslateYou/commit/4e5e0dd4ed062aa2866c81da9872d3e05a6311b7:
[ty.zip](https://github.com/Bnyro/TranslateYou/files/11650260/ty.zip)

**Comment by linsui** [comment]
It's reproducible!

**Comment by Bnyro** [comment]
Awesome! I guess F-Droid will just skip the current release and we continue as normal with the next build?

**Comment by linsui** [comment]
Yes, this version is disabled. The next version will be added automatically.

**Comment by Bnyro** [comment]
Thanks for your help!

**Comment by licaon-kter** [comment]
So it wants Java17: https://gitlab.com/fdroid/fdroiddata/-/jobs/4435473349#L296

I give it that: https://gitlab.com/fdroid/fdroiddata/-/commit/feea486b65159e3da0490e5f9b3dc13ab5d1fec7

But then it's not repro: https://gitlab.com/fdroid/fdroiddata/-/jobs/4435869992#L398 ?

**Comment by Bnyro** [comment]
v6.1 is broken due to the Java17 migration: It required proguard rules for Retrofit which I haven't been aware of, added them now and will create a new release shortly. Could that have been the issue?

**Comment by licaon-kter** [comment]
Not sure, the second link has Browse - tmp - apk you can compare
