### ISSUE TITLE
History: Delete individual entries

### ISSUE THREAD

**Issue by ManDay** [Bnyro/TranslateYou#271]
### Describe your suggested feature

If one tries different formulations until the best translation, it would be nice if previous ones could be deleted to keep the history clean from unneeded entries. Or, for privacy reasons, too.

I think a "Delete" icon-button next to each entry would be great, optimally with a "Entry deleted - Undo" pill like it's known from other applications.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can delete entries of the history by swiping to the right. To avoid having entries added that you don't want (due to typing), disable automatic translation in the settings.

**Comment by ManDay** [comment]
Thank you. Sorry I was not aware of the swipe gesture. There seems to be an associated UI issue though, as the deleted row remains blank. Should I file a bug for this?

**Comment by Bnyro** [comment]
Yes, likely.
