### ISSUE TITLE
History: List becomes malformed after swipe-deleting entries

### ISSUE THREAD

**Issue by ManDay** [Bnyro/TranslateYou#273]
### Steps to reproduce

- Submit a sequence of translations to fill the history with 3 or more entries.
- Swipe delete any but the oldest entry

### Expected behavior

- The deleted entry should disappear
- All non-deleted entries should remain
- Entries older than the swipe-deleted one should move one up

### Actual behavior

- The deleted entry disappears
- A blank list item appears in its place
- The next-older entry vanishes until history is re-opened the next time

### Translate You version

6.2

### Android version

LOS 19.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ManDay** [comment]
This is the result after deleting "Three tests" from a history which said
- Three tests
- Two tests
- One test

![Screenshot_20230616-190454_Translate You](https://github.com/Bnyro/TranslateYou/assets/1059827/fd8c3214-57cd-4ee5-b4a5-e15dc705e964)

**Comment by Bnyro** [comment]
Thanks for your help, I already found the issue, so no further testing is needed for now :)

**Comment by ManDay** [comment]
My goodness, you are quick :sweat_smile:
