### ISSUE TITLE
Definition, synonym and sentences?

### ISSUE THREAD

**Issue by Drangonfly30** [Bnyro/TranslateYou#28]
### Describe your suggested feature

In google translate when search a word it also shows other translation, definition, synonym, sentence etc. So, do you any plan of adding these? It'll be better to have these things if possible. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's planned for the future, however some engines (for example LibreTranslate) don't support such additional information. The app was initially meant to support LibreTranslate only and therefore I didn't implement those yet.
