### ISSUE TITLE
Add an export feature to the History section

### ISSUE THREAD

**Issue by Prasanta-Hembram** [Bnyro/TranslateYou#285]
### Describe your suggested feature

It would be great to add an export feature that allows **language learners** to export their translations in a variety of formats, such as Excel, txt, and make it possible to use in flashcard application like Ankidroid.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project.
