### ISSUE TITLE
Buttons looks faded

### ISSUE THREAD

**Issue by Drangonfly30** [Bnyro/TranslateYou#288]
### Steps to reproduce

1. Just open app

### Expected behavior

Text written on buttons should be visible

### Actual behavior

It looks really faded

![Screenshot_2023-07-15-04-08-16-893](https://github.com/Bnyro/TranslateYou/assets/113085944/49017f2d-7813-463a-89dd-3fb9b8147396)
![Screenshot_2023-07-15-04-17-45-976](https://github.com/Bnyro/TranslateYou/assets/113085944/3d00ea97-4e0d-4fb7-98ba-4d67b9582774)

### Translate You version

Latest v6.3

### Android version

Android 7.0

### Other details

The button looks like this on the setting page, over all app looks really faded and unpolished and ruins the overall experience even when the app is so good in functionality.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You should choose a different accent color on the top right in the settings.
