### ISSUE TITLE
[New API] Deepl

### ISSUE THREAD

**Issue by Ilithy** [Bnyro/TranslateYou#29]
### Describe your suggested feature

It would be great if Deepl could join, in the future, the group of translation engines supported by Translate You

* Their translation engine is excellent.
* It provides a Free API Key with a limit of 500,000 characters per month (which I think is pretty good).
* They respect user privacy.

Thanks you.

### Other details

[Deepl API - Introduction](https://www.deepl.com/en/docs-api/)

[Deepl API - Endpoint](https://www.deepl.com/docs-api/translate-text/translate-text/)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I would like to add it, but unfortunately I just figured out that creating an API key requires providing a valid credit card for identity verification which I'm not really in favor of to be honest.
Apart from that adding support for it shouldn't be a hard task

**Comment by Bnyro** [comment]
That depends. I could still try to add support for it, it's just very hard to say whether it works without being able to test it.
In theory their docs should be enough to get it working, but the users will always need to enter their own API key!

**Comment by Ilithy** [comment]
>That depends. I could still try to add support for it, it's just very hard to say whether it works without being able to test it.

If it needs to be tested, I could provide you with my own key, I registered for a free account

>the users will always need to enter their own API key!

Indeed, but the user does not have the obligation to register, or to use it, just the possibility to do it if he has an api key.
Maybe Deepl would be willing to provide you with a (free) api key to integrate directly into TY as a base (in addition to the possibility to use your own key) without having to provide a credit card, since you are working on a FOSS Android project.

**Comment by Bnyro** [comment]
> If it needs to be tested, I could provide you with my own key, I registered for a free account
> 
I appreciate that but it's probably better if I create my own one for testing purposes, maybe I'll grab one, but I'm gonna need to "inform" more about how trust worthy DeepL is.
In the worst case I'll have to code it blindly and let you test the debug builds afterwards :)
> Indeed, but the user does not have the obligation to register, or to use it, just the possibility to do it if he has an api key. Maybe Deepl would be willing to provide you with a (free) api key to integrate directly into TY as a base (in addition to the possibility for users to use your own key) without having to provide a credit card, since you are working on a FOSS Android project.
>
Well, since API keys are already "free" they probably wouldn't see a reason to create one for me in a different way, also because the app supports other translation engines than DeepL too :)

**Comment by Ilithy** [comment]
>I appreciate that but it's probably better if I create my own one for testing purposes, maybe I'll grab one, but I'm gonna need to "inform" more about how trust worthy DeepL is.
In the worst case I'll have to code it blindly and let you test the debug builds afterwards :)

It's up to you, it is with pleasure; it gives me a good excuse to ask you to integrate this engine 🫣

>Well, since API keys are already "free" they probably wouldn't see a reason to create one for me in a different way, also because the app supports other translation engines than DeepL too :)

yes, no cheating from Deepl, it warns that the api will return an error once the defined quota has been reached, no more; about that you are probably right 👍🙏

**Comment by Bnyro** [comment]
Feel free to reach out to me via Matrix if you want to/use it (@bnyro:matrix.org), otherwise we can go on discussing here :)

**Comment by Ilithy** [comment]
Thank you very much for this extremely fast addition. <3

**Comment by the4anoni** [comment]
Free API key doesn't work in Translate You. I am getting "Error with communicating with the server. Please choose another instance..."

Same API key works fine in FairEmail

**Comment by Ilithy** [comment]
>Free API key doesn't work in Translate You. I am getting "Error with communicating with the server. Please choose another instance..."

>Same API key works fine in FairEmail

No problem on my side (for info):

![Screenshot_20221028-114201](https://user-images.githubusercontent.com/36798218/198558078-b8f8ec0d-b74d-44fc-bacc-4d2cdfd9f92a.png)



- Pixel 6 pro
- Grapheneos/android 13
-TY version: 2.1
Source: Github

**Comment by the4anoni** [comment]
> > Free API key doesn't work in Translate You. I am getting "Error with communicating with the server. Please choose another instance..."
> 
> > Same API key works fine in FairEmail
> 
> No problem on my side (for info):
> 
> ![Screenshot_20221028-114201](https://user-images.githubusercontent.com/36798218/198558078-b8f8ec0d-b74d-44fc-bacc-4d2cdfd9f92a.png)
> 
> * Pixel 6 pro
> * Grapheneos/android 13
> * TY version 2.1
> * Source: Github

I have version 2.1 from IzzyOnDroid, my device is Galaxy S10 with LOS 20.
![Screenshot_20221028-115037_Translate You](https://user-images.githubusercontent.com/13403084/198559333-f3780f3c-645e-43ff-b35e-ac78bc64af84.png)

**Comment by the4anoni** [comment]
I didn't changed anything, today it works just fine 🎉
