### ISSUE TITLE
Translate image like in Google lens 

### ISSUE THREAD

**Issue by Justauser0** [Bnyro/TranslateYou#290]
### Describe your suggested feature

![Screenshot_2023-07-15-11-32-01-41](https://github.com/Bnyro/TranslateYou/assets/135147872/f85276bb-3b6a-4821-b4de-cfe6a65be1da)

![Screenshot_2023-07-15-11-32-57-69](https://github.com/Bnyro/TranslateYou/assets/135147872/19f90eb9-9eac-46d2-ad94-222e01ee9a83)

Look how does Translate you translate the image

![Screenshot_2023-07-15-11-36-49-91](https://github.com/Bnyro/TranslateYou/assets/135147872/4932f97c-a63b-4fbf-9d4a-bbec930d65a9)

Google lens image translation ui is much better

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Images can be translated with the button at the top right. Floating windows like in Lens are not planned from my side like discussed in other issues.
