### ISSUE TITLE
Default translation language pairs (optional)

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#297]
Sometimes I make translations in different languages and forget about the pair set to GER > ITA or other pairs I don’t use frequently.

I would like to have the possibility to set a default language pair every time I launch the app.

For example: ENG > ITA at each app launch (it should works only if one has previously closed the app if not, it shows just the last used).

![1000035213](https://github.com/Bnyro/TranslateYou/assets/113377431/23adb3d9-e4e2-4d16-a5d3-adac7c7a8f6d)

**Comment by Bnyro** [comment]
That's not planned, I recommend bookmarking the languages instead which makes it easier to find them.
