### ISSUE TITLE
add translation engines

### ISSUE THREAD

**Issue by Pantyhose-X** [Bnyro/TranslateYou#298]
### Describe your suggested feature

[apertium](https://apertium.org/) and [Lojban](https://mw.lojban.org/papri/Lojban)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use the proper issue template.
