### ISSUE TITLE
Error in communicating with the server

### ISSUE THREAD

**Issue by YuriiOlefir** [Bnyro/TranslateYou#304]
### Steps to reproduce

1. Install Translate You 6.3.
2. Set the `Lingva` translation engine in the settings.
3. Attempt to translate any message to any language.

4. The programme stopped translating with the error: "Error in communicating with the server".

### Expected behavior

The programme successfully translates using the `Lingva` engine.

### Actual behavior

The programme does not translate using the `Lingva` engine.

### Translate You version

6.3

### Android version

Android 12

### Other details

This happened more than a week ago, after updating to version `6.3`. The programme stopped translating any message using `Lingva` and `SimplyTranslate` translation engines. The list of languages for them is also not loaded.

API keys are not used.

Rolling back to the versions `6.2` and `5.2` does not solve the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The official instances of Lingva and SimplyTranslate are down currently. Either enter a different instance URL manually or switch to using different translation engines.
