### ISSUE TITLE
Use translation platform for app strings translation

### ISSUE THREAD

**Issue by yarons** [Bnyro/TranslateYou#32]
### Describe your suggested feature

Instead of manually translating the strings inside the values.xml we can use Weblate or any other localization tool to ease the contribution.

### Other details

These are the terms:
https://hosted.weblate.org/hosting/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I actually already set that up, I just forgot to add it to the README ;)
It can be found at https://hosted.weblate.org/projects/you-apps/translate-you/!
