### ISSUE TITLE
TY doesn't remember the last translate (couple) configuration

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#4]
I set ENG > ITA but every time I close app and after I open it again, TY loses the last configuration and begin always in Auto > Eng.

It also would be useful have a favorites list.

**Comment by Bnyro** [comment]
A favorites list wouldn't be that easy because some instances of LibreTranslate don't support some languages others do support, they always get fetched dynamically.
However, you're right, it makes sense to remember the last selected languages, I will work on that!
