### ISSUE TITLE
ux improvement

### ISSUE THREAD

**Issue by andsofine** [Bnyro/TranslateYou#42]
### Describe your suggested feature

move "Enable history and "Translation delay" higher than the choice of translation services. because of how it looks so far, it looks like there is a separate setting for each translation service

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, I'm not sure about that one:
Since the translation engine is the "most important" setting in my opinion, it should be at the top of the settings page.
Maybe it'd be a better idea to just increase the margin between the engine-specific and the normal settings?
