### ISSUE TITLE
Microphone permissions

### ISSUE THREAD

**Issue by popogomo** [Bnyro/TranslateYou#443]
### Steps to reproduce

Apologise for opening 2 issues at once.

What's the purpose of Microphone permissions if there is nothing in the UI to press and speak? My understanding is that this is required when the app has an ability to listen to speech and translate but there is no button for it in the UI.

### Expected behavior

There should be a button for it, or the permission needs to be removed.

### Actual behavior

No UI button and nothing in the settings indicating the need of Microphone permissons

### Translate You version

10.0

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> What's the purpose of Microphone permissions if there is nothing in the UI to press and speak?
>
The button only shows if your device has a Speech To Text service installed, either Google or other third party speech to text services supporting Android's STT Intent api, e.g. https://github.com/you-apps/TranslateYou/issues/421.
