### ISSUE TITLE
customize font size of translated text

### ISSUE THREAD

**Issue by ghost** [Bnyro/TranslateYou#444]
### Describe your suggested feature

In my opinion, font size of translated text is too big, but others can find it the opposite.
An option to change its size would be nice

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't agree that something like that should be customizable by the user, you can modify the overall font size it with the system's font size settings.
