### ISSUE TITLE
Translation Stopped Working On Graphene OS (Android 14)

### ISSUE THREAD

**Issue by Ronn-H** [Bnyro/TranslateYou#456]
### Steps to reproduce

1. Open the app on last build of Graphene OS 
2. Enter a word for translation (No matter which language)
3. Click on translate or wait if automatic translate is enabled
4. Progress Bar looks active but translation does not appear

### Expected behavior

Word should be translated to the requested language

### Actual behavior

No translation appear

### Translate You version

10

### Android version

Android 14

### Other details

The application worked perfectly on the phone, but suddenly stopped working lately.
It doesn't matter which tralsation engine is configured (I personally use Reverso).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Did you attempt clearing the app's cache?

**Comment by Ronn-H** [comment]
Yes. I have 👍
And also, uninstalled and reinstalled the app on my phone...

**Comment by kuriokurio** [comment]
Same thing happens to me, I realized it stopped working some time ago.

It also displays a small notice informing about an error with the connection to the servers.

Fairphone OS with Android 14 and app version 10.0 as well.

**Comment by mbbsas** [comment]
Same behaviour!
Lineageos 21 
Android 14
Translate you 7.0

**Comment by GitGitro** [comment]
I see you all have privacy conscious ROMs.
I'm just assuming here, but by chance are you all using a VPN service?

I noticed with my VPN and Reverso Engine that it returns a 403 error saying that the ip is blacklisted.
For you i suggest to use mozhi and the enginge you prefer, for the devs maybe a try catch to intercept those HttpExceptions?
I've tried to implement it myself but without results :(

**Comment by tom-schi** [comment]
I can confirm that this bug also occurs on my phone. I don't use a VPN, and I'm running e.os 2.5 on Android 13. It worked fine before, but I don't know when it stopped working since I don't use app that often. I tried downgrading to versions 10 and 9, but the problem persists.

**Comment by Bnyro** [comment]
Tried all engines?

**Comment by Bnyro** [comment]
Including app restarts after switching engine and clearing the cache?
