### ISSUE TITLE
Only the first 4 lines of each thread in the history

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#48]
### Describe your suggested feature

In my humble opinion there is no need to show the whole thread in the history: just make the first four lines visible.

It improves the look, the sense of order, and the immediacy of looking for something among so many other things. It also turns out to be more compact.

![Screenshot_2022-10-17-07-49-33-36_23ac93267c0fe78a3ab35e3ff4008864 (1)](https://user-images.githubusercontent.com/113377431/196099290-71f44489-15f4-4238-95c7-fda68d61f57a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ilithy** [comment]
That would be very good, thank you very much 🙏

**Comment by Bnyro** [comment]
Umm, could anyone please come up with an idea how to call such an option? My creativity sucks at that point, only thing I imagined was "Legacy history" which kinda says nothing about what it actually does :joy:

**Comment by Bnyro** [comment]
> History thread resizer ?!?!?
> 
> I am a foreigner and do not speak English well. Tell me if it can be adjusted better.

Hmm, not sure since it's actually more (which you couldn't now) :)

As for now, there are only the first three lines shown in the history, but when clicking it a dialog opens including both whole texts (the inserted one and its translation). Apart from that there now is a button in the dialog to "open" the text, which means it'll paste the text you've been inserting into the normal translation text field (where you usually insert your text).

So if adding an option we somehow need to mention parts of that too maybe, idk

**Comment by Ilithy** [comment]
>Umm, could anyone please come up with an idea how to call such an option?

Personally I would have named this option `full history view`, what do you think?

>Apart from that there now is a button in the dialog to "open" the text, which means it'll paste the text you've been inserting into the normal translation text field (where you usually insert your text).

>So if adding an option we somehow need to mention parts of that too maybe, idk

Do you plan to change this behavior by enabling the full history view option?

**Comment by Bnyro** [comment]
> Do you plan to change this behavior by enabling the full history view option?
>
Yes, it would then skip the dialog and directly reopen the translation view with the text inserted!

**Comment by Bnyro** [comment]
Kk, added now, it's called `Compact history`, turning it off will result in the old behavior :)

**Comment by Bnyro** [comment]
> Do you have a your own fdroid repo?

I don't and Ilithy probably doesn't either unfortunately, Ilithy probably built the app manually :)

**Comment by Bnyro** [comment]
Yeah, that's what I've been talking about too. The app is available on IzzyOnDroid but I don't have my own repo.
