### ISSUE TITLE
Floating button hides me the translation result

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#5]
As the image shows, the "new translation" button occupies a large part of the bottom screen going to obscure the result of the translation preventing its optimal display.

I therefore request that the size of the button be reduced and that it be round. Possibly moved to a place where it does not bother.

![Screenshot_2022-09-30-20-21-09-30_fbcdf42ed509c3884e299b0f88be1eba (1)](https://user-images.githubusercontent.com/113377431/193333235-0996b3b8-cfbc-4e45-8462-dacce69de4ae.jpg)

**Comment by Bnyro** [comment]
Yeah, that could be a good idea, I'll add change that soon :)
