### ISSUE TITLE
Lingva didn't work well with non-Latin words in TY 2.x

### ISSUE THREAD

**Issue by raymond-nee** [Bnyro/TranslateYou#59]
### Steps to reproduce

1. Use the lingva engine in TY Settings
2. Type some non-Latin word, like Chinese or Russian

### Expected behavior

The input should be translated into the target language.

### Actual behavior

The result just repeated the original input.
When open the additional infomation switch, it also didn't show the detected language right.

### Translate You version

2.1

### Android version

Android 12

### Other details

**Screenshot** 
- When translate the Chinese word into English
![Screenshot_2022-10-23-16-36-43-552_com bnyro translate nf-edit](https://user-images.githubusercontent.com/9211781/197383730-d699bae6-8cab-408b-af72-a2d0c4bbc324.jpg)

- When use Russian
![Screenshot_2022-10-23-17-11-02-291_com bnyro translate nf-edit](https://user-images.githubusercontent.com/9211781/197384040-a397ade0-ce50-454c-9e70-8d2972b739e0.jpg)

Tried to change the lingva instance and it didn't work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please retry it with version 1.6?

**Comment by raymond-nee** [comment]
> Could you please retry it with version 1.6?

Just retried with v1.6, it works well.

![Screenshot_2022-10-23-18-01-47-340_com.bnyro.translate.nf-edit.jpg](https://user-images.githubusercontent.com/9211781/197386084-0f8ffd2b-913e-4ca9-83cc-8c4ea82cff33.jpg)

**Comment by Bnyro** [comment]
Okay, thank you for testing, then I probably know what the issue is.
Unfortunately the only way to fix it will probably break https://github.com/Bnyro/TranslateYou/issues/38 :/
Selecting the source language manually doesn't work either with non-latin languages, does it?

**Comment by raymond-nee** [comment]
> Selecting the source language manually doesn't work either with non-latin languages, does it?

No, it doesn't.
