### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TeaqariaWTF** [Bnyro/TranslateYou#6]
Why isn't there an option to choose a different language?
Only Auto --> English active

ArrowOS Android 12.1

![Screenshot_20221001-003913_Translate You](https://user-images.githubusercontent.com/90970076/193360013-18d40725-3cb7-4a61-bc88-1c953440053c.png)

**Comment by Bnyro** [comment]
Looks like the default selected instance is not available from your region. You can change it when navigating to the options on the three dots on the top right. A list of instances can be found [here](https://github.com/LibreTranslate/LibreTranslate#mirrors).
