### ISSUE TITLE
Reverso Context Engine

### ISSUE THREAD

**Issue by GitGitro** [Bnyro/TranslateYou#60]
### General informations

I was wondering if you could implement reverso context as an engine in the non-libre version.
It doesn't have a public api and the issue is I don't know if it has rate limits or requires an api key.
If you can add it it would be really nice since it has accurate translations, and with a button in the setting you could maybe enable to see the multiple translations it provides for a single word and the translation samples/contexts, similar to the definitions and synonyms you recently added.

### Translation engine service endpoints

https://api.reverso.net/translate/v1/translation

### Acknowledgements

- [X] I have searched the existing requests and this is a new ticket, **NOT** a duplicate or related to another open or closed request.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yeah, adding support for it will be possible.
The issue with it is that
1. There's no public endpoint (at least I couldn't find one) to fetch the available languages so we have to hard code them.
2. It uses a different request format so that it won't be working well in combination with other engines in the simultaneous translation

Note to self: https://github.com/s0ftik3/reverso-api/blob/master/src/reverso.js#L383-L400

**Comment by Bnyro** [comment]
Found another example for myself: https://codeberg.org/SimpleWeb/SimplyTranslate-Engines/src/branch/master/simplytranslate_engines/reverso.py

**Comment by Bnyro** [comment]
> Oh well if it's too much trouble don't bother it's not that important. Hard coding the languages also doesn't look clean. I'll leave up to you :)

We might be able to get Reverso support on board by implementing #61, but I'll probably add direct support for Reverso without a third party instance as well :)

PS: I'm currently in vacation and don't have my PC with me so don't expect anything before next Sunday or so :wink:

**Comment by Bnyro** [comment]
It's been a bit harder than I thought (had some fun debugging :joy:), but in the end it's working now :tada: 
I'm planning to publish a new release as soon as I fixed some minor bugs :)

**Comment by Bnyro** [comment]
> Thank you so much! tada Do you have paypal?
>
Sure, but I won't expose it :wink:

I'm honored enough to be able to have some people in the community caring about my work and benefiting from it, that's what keeps motivating me and apparently other developers as well to work on some FOSS projects :)

So thank you for being here (and other readers as well of course) <3

**Comment by Bnyro** [comment]
Though, donating to one's favorite Linux distro maintainers is never a bad idea if you have some euros left 😜

**Comment by Bnyro** [comment]
> Yeah that wasn't my plan ahahah, just wanted to offer you a few coffees to keep you awake and coding
>
I got that haha, my message should have been that I prefer to not receive donations, I just figured out that "expose" probably was the wrong term in that context so it was not meant like that :wink:

> Thank you again for your efforts
>
You're welcome, I usually enjoy coding so I benefit as well <3

PS: I prefer tea ;)
