### ISSUE TITLE
Change order of translation engines

### ISSUE THREAD

**Issue by Donkey-Doug** [Bnyro/TranslateYou#62]
### Describe your suggested feature

Make it possible to change the order of the engines

### Other details

This way I can set my preferred engine as default choice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The default chosen engine for the simultaneous translation is the one you currently selected at the top, I don't really see a good reason to allow reordering them as this would also require me to rewrite major parts of the code.
