### ISSUE TITLE
LibreTranslate: Auto doesn't show result

### ISSUE THREAD

**Issue by Johnny5sword** [Bnyro/TranslateYou#64]
### Steps to reproduce

1. Choose "Auto" as source & "English" as output language
2. Type "Uno" & wait / Highlight text, pick Translate You Libre & wait

### Expected behavior

The translated language would be shown.

### Actual behavior

No results show up even after waiting or adjusting the translation delay in the settings.

### Translate You version

Libre 1.8 

### Android version

11

### Other details

https://user-images.githubusercontent.com/112535244/198842094-d3dc4aef-74ce-40d2-ae2c-64adc4220a46.mp4

If I change the source to a specific language, the results would show.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Johnny5sword** [comment]
Nvm, I didn't notice a new update in F-Droid because of a certificate error so I had to uninstall the app first.
After updating to 2.1, the issue is no more.

**Comment by Arne19** [comment]
Hi, first of all, thanks for your apps!
I'm just having this issue with the monocles libretranslate instance and I'm not sure what's the reason. Here's the log:

I/okhttp.OkHttpClient: {"detectedLanguage":{"confidence":95.0,"language":"pt"},"translatedText":"Hallo, ich that Spargel"}
I/okhttp.OkHttpClient: <-- END HTTP (100-byte body)
E/error: Unexpected JSON token at offset 34: Unexpected symbol '.' in numeric literal at path: $.detectedLanguage.confidence
    JSON input: {"detectedLanguage":{"confidence":95.0,"language":"pt"},"translatedText":"Hallo, ich that Spargel"}

When manually choosing a language it works. Both, building the app from source and running the latest f-droid version seem to have this problem.
