### ISSUE TITLE
Reverso Context: multiple translations per word and example translation

### ISSUE THREAD

**Issue by GitGitro** [Bnyro/TranslateYou#66]
### Describe your suggested feature

Usually when translating with reverso for a single word it gives you back a list of words/synonyms, to be more precise in the response json it's under contextResults -> results
Would it be possible to have a toggle to display more results?

And if it doesn't become too cluttered the translation of the example would be really nice (always under results -> source examples and target examples)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You should be able to see already some of that information when turning on `Additional information` in the settings, for now it should only show the source examples because I forgot to change that when testing ;)

**Comment by Bnyro** [comment]
Oh, sure, we can include those as well!
