### ISSUE TITLE
"Odia" Translation has been completed.

### ISSUE THREAD

**Issue by GET100PERCENT** [Bnyro/TranslateYou#69]
### Describe your suggested feature

I have completed "odia" translation for the application using weblate. Add it to the application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It gets added automatically ...

**Comment by GET100PERCENT** [comment]
Okay

**Comment by GET100PERCENT** [comment]
![chrome_screenshot_7 Nov 2022 18_38_12 GMT+05_30.png](https://user-images.githubusercontent.com/116144024/200319510-d723f464-d4f5-448b-83c4-93abbeda7000.png)

**Comment by GET100PERCENT** [comment]
What is the red crossmark there near the Odia translation?
What does it mean?

**Comment by GET100PERCENT** [comment]
It's already 100% completed, so why is that crossmark there?
Will it be not added to the application?

**Comment by Bnyro** [comment]
That github action checks failed but that was already the case before the translation, it's not related to your translations though

**Comment by Bnyro** [comment]
Yes, it's gonna be in the next update :)

**Comment by GET100PERCENT** [comment]
Okay 👍

**Comment by GET100PERCENT** [comment]
How to change the application's language in the recent version 2.3?

**Comment by Bnyro** [comment]
It follows your device's language!

**Comment by GET100PERCENT** [comment]
Okay
