### ISSUE TITLE
Hidden menù to launch/manage hidden apps

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#7]
Since we live in times when we may need to hide something (you never know what kind of government we will have) I thought of a function that has nothing to do with translations.

As such, TY will have the app function that allows access to hidden apps by writing a "magic" phrase.

In other words if I type (for example) "bin salabin" a hidden menu will open which will allow:

- hide/show apps
- launch hidden apps

The magic phrase that allows the secret menu to be opened should be arbitrarily decided by the user (it could also be a long password).

Of course this is not a priority.

What do you think about it?

**Comment by Bnyro** [comment]
Hmm, I think that would be something for an assistant that includes more features than translation only, for example https://f-droid.org/en/packages/org.dicio.dicio_android/.
Since the app is only meant to be there for translations, I think that this would be off the goal of the project.

**Comment by Bnyro** [comment]
I think the better way for that would be to use a third party launcher that supports something like that or a separate app that is just covered by an unobtrusive name and icon. As far as I know there are some launchers that have got such features!
