### ISSUE TITLE
add search bar to language selection menu

### ISSUE THREAD

**Issue by aleksoybin** [Bnyro/TranslateYou#74]
### Describe your suggested feature

I have just downloaded your app, and it's awesome, keep up the good work. the one thing that is missing for me however is a search bar in the language selection menus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't have an idea how to add a search bar while keeping the dialog look good and providing a good user experience, hence I'm closing the issue for now. As bookmarks for languages got added now, you should just search the ones you use once and then use them via bookmarks.
