### ISSUE TITLE
add language history

### ISSUE THREAD

**Issue by aleksoybin** [Bnyro/TranslateYou#75]
### Describe your suggested feature

in addition to my previous feature request, a language history in the same menu with a thin line separating the maybe 5 recent languages and the full language list would make the user experience a lot better, in my opinion

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by aleksoybin** [comment]
or maybe a pinned languages list would be better, or maybe both, with a history box between the proposed search bar and a pinned languages list :p

**Comment by Bnyro** [comment]
I've added the ability to bookmark languages now, a history of recently used languages shouldn't be needed anymore as you usually use only 5 languages at maximum and thus the history and the bookmarked languages would be pretty similar then.
