### ISSUE TITLE
add some separation between the translation, detected language, and definitiom boxes

### ISSUE THREAD

**Issue by aleksoybin** [Bnyro/TranslateYou#76]
### Describe your suggested feature

I think that a separation of the translation, detected language, definition, and example boxes would make the app look a lot better and easier on the eyes. I propose something like 1/3 the difference between the translation box and the actual app background for the detected language box, and 2/3 the difference for the definition box
![homescreen](https://user-images.githubusercontent.com/117856662/200939238-ac604b24-dfc8-4273-875b-098f7366fcb4.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't really want to make the inserted text background differ from the one of the translated text, just doesn't look too good in my opinion.
However, using an `elevated card` for each of the information items at the bottom seems like a good idea to me and thus I'm probably gonna change it that way :)
