### ISSUE TITLE
english words translated are not properly highlighted in the definition box

### ISSUE THREAD

**Issue by aleksoybin** [Bnyro/TranslateYou#77]
### Steps to reproduce

1. translate a word from english to another language
2. scroll down a little and look for the word you just translated
3. observe

### Expected behavior

the translated word should be highlighted

### Actual behavior

the translated word is wrapped in html bold text tags

### Translate You version

2.3

### Android version

13

### Other details

![boldtags](https://user-images.githubusercontent.com/117856662/200940774-78c2f276-057f-4f20-bcc5-27646f2f7873.JPG)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fixed with https://github.com/Bnyro/TranslateYou/commit/fb4f166c3dbfe6accb6dd1be59721e057d79b2f1 :)
