### ISSUE TITLE
The translated text can't be seen

### ISSUE THREAD

**Issue by GET100PERCENT** [Bnyro/TranslateYou#79]
### Steps to reproduce

1. First select a large text and past it in the app.
2. Try to scroll down and see the translated text.

### Expected behavior

It should be scrolled and seen.

### Actual behavior

Only the original text gets scrolled, can't scroll to see the translated text.

### Translate You version

2.3

### Android version

7.1

### Other details

Download "ScreenRecording_20221111_130547.mp4" with Send: simple, safe file sharing https://send.zcyph.cc/download/ad74d6b1c16a3b84/#aasH8zt1FipxZvUko_zpxw
In the above video you can understand the issue more clearly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
related: #12

**Comment by Bnyro** [comment]
Hmm, the video can't be downloaded anymore unfortunately (at least it doesn't for me), would be nice if you could send it once again :)

**Comment by Bnyro** [comment]
Sorry for the inconvenience

**Comment by GET100PERCENT** [comment]
https://user-images.githubusercontent.com/116144024/205254601-4695dab3-1d31-4819-b777-5eff79c9fac1.mp4

This is the video showing the bug.
