### ISSUE TITLE
the language

### ISSUE THREAD

**Issue by Russell1525270262** [Bnyro/TranslateYou#80]
### Describe your suggested feature

Please sir add bangla language 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Languages are fetched dynamically depending on the translation provider you select in the settings. The app itself can be translated at https://hosted.weblate.org/projects/you-apps/translate-you/.
