### ISSUE TITLE
Offline ditctionary

### ISSUE THREAD

**Issue by Crisis82** [Bnyro/TranslateYou#81]
### Describe your suggested feature

I'm currently using the Libre version and I'm curios if there could be a possibility to download an entire language dictionary for an offline use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I couldn't find a way to make it work as there's no public offline database compatible with Android, see #18.
