### ISSUE TITLE
UI rotating language selection button

### ISSUE THREAD

**Issue by basings** [Bnyro/TranslateYou#89]
### Describe your suggested feature

Hey, I'm sorry for my following description. I hope it's comprehensive.

What do you think of changing the language buttons + popup to a rotating button like the numbers on a padlock? Swiping up would scroll down in the list of languages and swiping down scrolls up. In addition to that, you can also keep the tap behavior in order to select favs like now.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, I don't really get you unfortunately. Some screenshots of the app with your suggested drawn as a sketch inside might help understanding it :)

**Comment by Bnyro** [comment]
Closing this for now as I don't get the point unfortunately, feel free to reopen when you have some more detailed info or some drafts to share with me :)

**Comment by basings** [comment]
I finally found an app that implemented what I tried to write in words. The app is called QRalarm https://www.f-droid.org/en/packages/com.sweak.qralarm/ Here's a video of it https://drive.proton.me/urls/K72VW7629C#6-UbJkj7nl0v instead of the clock/ numbers it should rotate between languages of course.

**Comment by Bnyro** [comment]
Oh, now I got you. However, I don't think that would be user friendly since for that, we would need to remove the search and the bookmarks feature, since that swiping gesture wouldn't allow that. Apart from that that would probably be annoying for users to have to go through all languages before finding the one they searched.
