### ISSUE TITLE
Wrong link for IzzyOnDroid

### ISSUE THREAD

**Issue by smaragdus** [Bnyro/TranslateYou#9]
The **IzzyOnDroid** [link](https://apt.izzysoft.de/fdroid/index/apk/com.bnyro.translateyou)  is 404 (**App not found.**).

- [current wrong link](https://apt.izzysoft.de/fdroid/index/apk/com.bnyro.translateyou) 
- [actual right link](https://apt.izzysoft.de/fdroid/index/apk/com.bnyro.translate) 

I noticed this so I report it.

**Comment by Bnyro** [comment]
Oh, right, updated, thank you!

**Comment by smaragdus** [comment]
@Bnyro 

Thank you for your good work on this app and on [LibreTube](https://github.com/libre-tube/LibreTube), much appreciated!

**Comment by Bnyro** [comment]
> @Bnyro
> 
> Thank you for your good work on this app and on [LibreTube](https://github.com/libre-tube/LibreTube), much appreciated!

Thank you, happy you enjoy using LT and TY <3
