### ISSUE TITLE
History is broken

### ISSUE THREAD

**Issue by Drangonfly30** [Bnyro/TranslateYou#90]
### Steps to reproduce

1. Translate a word
2. Check history

### Expected behavior

It should only save history of whole word.
![Screenshot_2022-11-27-17-11-46-121](https://user-images.githubusercontent.com/113085944/204133595-d284174c-d570-4a2b-9c28-d894ac7dde93.jpeg)

### Actual behavior

It saves history of each alphabet.

### Translate You version

Latest

### Android version

Android 7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's getting saved every time the translation is fetched. In order to fix it you need to increase the `translation delay` in the app's settings ;)
