### ISSUE TITLE
Search language

### ISSUE THREAD

**Issue by glemco** [Bnyro/TranslateYou#92]
### Describe your suggested feature

It would be really nice if while selecting the lenguage, a search bar could let the user type the initials of the language. Especially on Lingva, there are really too many languages and finding the desired one takes time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As I've already stated out in #74, I don't think a search is needed anymore since bookmarks are now possible. Apart from that I wouldn't have an idea where to put the search bar as placing it inside the dialog would probably look weird. Anyways, if you have some viable suggestions I'm open for it!

**Comment by glemco** [comment]
Sorry, missed the duplicate issue..
Well many translator apps have this possibility, showing the search bar on top of the list. Although bookmarks make it convenient, a search bar would be nice if I'm trying a language I don't use often (and didn't bookmark before).
This is how they do in deepl, it doesn't look that weird or unintuitive to me (sorry for the Italian language but I guess with the symbol it's quite understandable).
![Screenshot_20221129-124136_DeepL](https://user-images.githubusercontent.com/32201227/204592402-90b24e4c-fef8-4b56-94a9-63bd3f427835.png)
