### ISSUE TITLE
History quick access button

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#96]
I would like to have a button through which I fastly reach history translations because I often need of it. 
This will be optional (on/off).

![Screenshot_2022-11-29-04-58-41-76_fbcdf42ed509c3884e299b0f88be1eba (1)](https://user-images.githubusercontent.com/113377431/204435741-4121fc88-8206-497c-9c42-96f873114bbb.jpg)

**Comment by Bnyro** [comment]
Sorry, I don't think that would be really useful as the history is always only two clicks away anyways.
Apart from that the space on the top is reserved for actions that can be applied to the current translation or inserted text.
