### ISSUE TITLE
Set UI language different from system one

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#97]
I have selected Italian as language for system UI but I would like to have English in TY as default.

Can you implement it?

**Comment by Bnyro** [comment]
Which Android version are you using? Since A13 devs can add support for changing the language of an app via the Android settings which would be easier than adding an option inside the app.

**Comment by Bnyro** [comment]
KK, then we'll need an in-app solution. I already implemented that once for another app so it should be doable :)
